#if you wanna change timezone just copy one of /usr/share/zoneinfo/place to /etc/localtime

#ip
alias ip='ip -c'

#exit
alias e='disown; exit'


alias ,.='!!'

# mpv 
alias mpvl='mpv --ytdl-format=43'

#Micrcontroller 
alias serial='micronucleus --run ~/Sync/Programming/serial.hex'

alias yt='mpsyt'

# SDR
alias sdr='gqrx-alsa'
# Disable mouse
alias remouse='sudo modprobe -r bcm5974'
alias enmouse='sudo modprobe bcm5974 && ~/bin/mousefix'

# Notes
alias notes='cd ~/Sync/Notes/EE2'

#quiet
alias quiet='sudo hdparm -y /dev/sda'

#zombify
alias zombify='sudo -u dork /home/vasko/dorknet/dork zombify'

alias radiorock="unbuffer mpv 'http://relay.181.fm:8028' |grep --line-buffered icy-title | sed -u 's/.*icy-title: /p/' > /tmp/panel-fifo"
alias radio40="unbuffer mpv 'http://relay.181.fm:8070' |grep --line-buffered icy-title | sed -u 's/.*icy-title: /p/' > /tmp/panel-fifo"
alias radiolounge="unbuffer mpv 'http://sc-tcl.1.fm:8010/' |grep --line-buffered icy-title | sed -u 's/.*icy-title: /p/' > /tmp/panel-fifo"
alias irc='autossh -M 0 -o "ServerAliveInterval 45" -o "ServerAliveCountMax 2" -p 55022 vasko@skozl.com'
alias vps='mosh vasko@108.61.173.91 -- screen -rd'
alias desk='mosh -p 55101:55999 --ssh="ssh -p 55022" vsz@108.61.173.91 -- screen -rd'
alias sourcel='source ~/.bash_aliases'
alias ,.='fc -e -'
alias cd..='cd ..'
alias nkill='pkill -f'
alias drop='/home/vasko/drop/dropbox_uploader.sh'
alias lo='libreoffice'
alias tuner='lingot'
alias efbterm='export TERM=fbterm'
alias listd='ls -al /dev/disk/by-uuid/*'
alias py='python3'
alias scan='iwlist wlp2s0 scan'
alias connect='sudo iwconfig wlan0 essid'
alias home='cd /home/vasko'
alias l='ls --color=auto'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias d='ls'
alias dm='ls | more'
alias n='clear'
alias s='sudo'
alias m='mv'
alias r='rm'
alias md='mkdir'
alias rd='rm -rf'
alias c='gcp'
alias v='vim'
alias sv='sudo vim'
alias f='gnome-commander'
alias o='less'
alias g='wget'
alias x='tar -xvzf'
alias a='tar -cvzf'
alias i='yaourt -S'
alias p='sudo pacman -Rs'
alias clean='sudo pacman -Rsn $(pacman -Qdtq)'
alias t='optirun'
alias ts='optirun -b none nvidia-settings -c :8'
alias tc='lsof -n /dev/nvidia0'
alias endsu='exit & sudo su'
alias iso='dd if=/dev/cdrom of=~/cdrom_image.iso'
#alias glxspheres='vblank_mode=0 /opt/VirtualGL/bin/glxspheres64'
alias tglxspheres='vblank_mode=0 optirun -vv /opt/VirtualGL/bin/glxspheres64'
alias pglxspheres='vblank_mode=0 primusrun /opt/VirtualGL/bin/glxspheres64'
alias httpserve='python -m SimpleHTTPServer'
alias pi='ping -4 google.com'
alias pl='ping 8.8.8.8'
alias def='sdcv'

 
alias aria2c='aria2c -c -x5 -s10 -m0'


#msf
alias msfconsole="msfconsole --quiet -x \"db_connect ${USER}@msf\""

# Screen
alias scradmin='$HOME/.tools/screen_run admin'
alias scrschool='$HOME/.ratpoison/screen_run school'


# Switch layouts
alias qwerty='setxkbmap us'
alias bgkey='setxkbmap bg'
alias colemak='setxkbmap uc -variant colemak && xset r 64 && xset r rate 170 60'
alias extmak='setxkbmap us4 -variant colemak && xset r 64 && xset r rate 170 60'
alias svenmak='setxkbmap us2 -variant colemak'
alias ansi='setxkbmap us3 -variant colemak'

# Make mount give all users right permission
alias mount='mount -o gid=users,fmask=113,dmask=002'  

# Alias FTP mount
alias ftpmount='curlftpfs eu5.org ~/ftp/' 
alias ftpumount='umount /home/vasko/ftp'

alias cbb='cat /proc/acpi/bbswitch' 
alias vimrc='vim ~/.vimrc'
alias uzblrc='vim ~/.config/uzbl/config'
alias aliases='vim ~/.bash_aliases'
alias solarize='~/.solarized/solarize'
alias rat='vim ~/.tools/ratpoisonrc.conf'
alias sx='vim ~/.config/sxhkd/sxhkdrc'
alias bs='vim ~/.config/bspwm/bspwmrc'
alias screenrc='vim ~/.ratpoison/screenrc'
alias xkb='sudo vim /usr/share/X11/xkb/symbols/vaskozl'
alias pdf='apvlv'
alias kpaint='kolourpaint'
alias gnu='vrms'
alias layout='vim .rat_layout'
alias lightdm='sudo /etc/init.d/lightdm start'
alias mountem='sudo mount -t auto /dev/sda5 /mnt/sda5'
alias grub='sudo -e /etc/default/grub'
alias reboot='sudo reboot'

# Games
#alias minecraft='optirun java -Xmx1024M -Xms1024M -XX:+UseFastAccessorMethods -XX:+AggressiveOpts  -XX:+DisableExplicitGC -XX:+UseAdaptiveGCBoundary -XX:MaxGCPauseMillis=500 -XX:SurvivorRatio=16 -XX:+UseParallelGC -XX:UseSSE=3 -XX:ParallelGCThreads=2 -jar ~/.minecraft/launcher.jar'
alias amnesia='optirun /usr/games/Amnesia/Launcher.bin'
alias nethackterm='rxvt -bg black -fg green +tr &'
alias cfgpanel=' fgpanel --fg-root=/usr/share/games/flightgear --panel=Aircraft/c172p/Panels/FGPanel_c172p.xml'
alias cfgfs='optirun fgfs --generic=socket,out,20,127.0.0.1,34200,udp,../Aircraft/c172p/Panels/FGPanel_Protocol_c172p'
#alias xonotic='cd ~/.Xonotic && optirun ~/.Xonotic/xonotic-linux64-glx -sessionid vaskozl'
alias blizz='wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Battle.net/Battle.net.exe'
alias starcraft='wine ~/.wine/drive_c/Program\ Files\ \(x86\)/StarCraft\ II/Support64/SC2Switcher_x64.exe'
alias lotv='wine "/home/vasko/.wine/drive_c/Program Files (x86)/StarCraft II - Legacy of the Void Beta/Support/SC2Switcher.exe"'

# Network tools

#scan available networks
alias wifi='sudo wpa_supplicant -i wlp2s0 -c /etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf'

alias ipscan='nmap -sP'
alias localscan='sudo nmap -PR -sP 192.168.0.1/24'
alias wifires='modprobe ipw2100'

# Drawing
alias mspaint='/usr/share/playonlinux/playonlinux --run "Microsoft paint"'
alias msexcel='/usr/share/playonlinux/playonlinux --run "Microsoft Excel 2010"'
alias msword='/usr/share/playonlinux/playonlinux --run "Microsoft Word 2010"'

# Aliases 

alias alc='vim ~/Sync/Notes/EE2/Algorithms-and-Complexity.md            '
alias ald='vim ~/Sync/Notes/EE2/Algorithms-and-Data-Structures.md       '
alias ana='vim ~/Sync/Notes/EE2/Analogue-Electronics-2.md               '
alias com='vim ~/Sync/Notes/EE2/Communication-Systems.md                '
alias con='vim ~/Sync/Notes/EE2/Control-Engineering.md                  '
alias dev='vim ~/Sync/Notes/EE2/Devices.md                              '
alias dig='vim ~/Sync/Notes/EE2/Digital-Electronics-2.md                '
alias fie='vim ~/Sync/Notes/EE2/Fields.md                               '
alias arc='vim ~/Sync/Notes/EE2/Introduction-to-Computer-Architecture.md'
alias mata='vim ~/Sync/Notes/EE2/Mathematics-2a.md                       '
alias matb='vim ~/Sync/Notes/EE2/Mathematics-2b.md                       '
alias matc='vim ~/Sync/Notes/EE2/Mathematics-2c.md                       '
alias pow='vim ~/Sync/Notes/EE2/Power-Engineering.md                    '
alias sig='vim ~/Sync/Notes/EE2/Signals-and-Linear-Systems.md           '
