#> /dev/null  Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd extendedglob correct
unsetopt beep
bindkey -e
zstyle ':completion:*' menu select
#zstyle ':completion:*' format '%BCompleting %d%b'
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/vsz/.zshrc'

autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# End of lines added by compinstall

source ~/.bash_aliases

# Minimise the ESC timeout
KEYTIMEOUT=2

export GPGKEY="895134C5"
export PATH="$HOME/bin:$PATH"
export EDITOR="vim"
export LD_LIBRARY_PATH=/usr/local/lib

PROMPT="%{$fg_no_bold[yellow]%}%1~ %{$reset_color%}▶ "
#RPROMPT="[%{$fg_no_bold[yellow]%}%?%{$reset_color%}]"


#Enable highlightling and completion like fish
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=match_prev_cmd
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}  

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      alias dir='dir --color=auto'
      #alias vdir='vdir --color=auto'

      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
fi

export ANDROID_HOME=/opt/android-sdk



#case $TERM in
#  (*rxvt*)
#
#    # Write some info to terminal title.
#    # This is seen when the shell prompts for input.
#    function precmd {
#    print -Pn "\e]0;%(1j,%j job%(2j|s|); ,)%1~\a"
#    #timeout --signal=KILL 1s ~/dotfiles/Panel/lemonbar/windows 
#    }
#    # Write command and args to terminal title.
#    # This is seen while the shell waits for a command to complete.
#    function preexec {
#    printf "\033]0;%s\a" "$1"
#    }
#
#  ;;
#esac

## Fancy sysinfo
#~/bin/sysinfo

bindkey "e[1~" beginning-of-line
bindkey "e[4~" end-of-line
# Control arrow keys
bindkey '^[[1;5C' emacs-forward-word
bindkey '^[[1;5D' emacs-backward-word

archey4
