# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd extendedglob correct
unsetopt beep
bindkey -e
zstyle ':completion:*' menu select
#zstyle ':completion:*' format '%BCompleting %d%b'
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/vasko/.zshrc'

autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# End of lines added by compinstall

source ~/.bash_aliases

#export PS1='%n@%m:%~%% ' 

export GPGKEY="895134C5"
export PATH="$HOME/bin:$PATH"
export EDITOR="nvim"
export BROWSER="~/.ratposon/firesend"
export LD_LIBRARY_PATH=/usr/local/lib
export wiki_browser='firefox'

PROMPT="%{$fg_no_bold[yellow]%}%1~ %{$reset_color%}☢ "
RPROMPT="[%{$fg_no_bold[yellow]%}%?%{$reset_color%}]"


#Enable highlightling and completion like fish
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=match_prev_cmd
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}  

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      alias dir='dir --color=auto'
      #alias vdir='vdir --color=auto'

      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
fi

export ANDROID_HOME=/opt/android-sdk


~/bin/sysinfo

case $TERM in
  (*xterm* | *rxvt*)

    # Write some info to terminal title.
    # This is seen when the shell prompts for input.
    function precmd {
if pgrep "panel" > /dev/null
then
      print -Pn "\e]0;%(1j,%j job%(2j|s|); ,)%1~\a"
      ~/dotfiles/Panel/lemonbar/windows
fi
    }
    # Write command and args to terminal title.
    # This is seen while the shell waits for a command to complete.
    function preexec {
if pgrep "panel" > /dev/null
then
      printf "\033]0;%s\a" "$1"
      ~/dotfiles/Panel/lemonbar/windows
fi
    }

  ;;
esac
