#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "bluetooth" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "bluebugger" "urxvt -e bash -c 'bluebugger -h && zsh'" \
           "bluelog" "urxvt -e bash -c 'bluelog -h && zsh'" \
           "bluepot" "urxvt -e bash -c 'bluepot && zsh'" \
           "blueprint" "urxvt -e bash -c 'blueprint -h && zsh'" \
           "blueranger" "urxvt -e bash -c 'blueranger && zsh'" \
           "bluescan" "urxvt -e bash -c 'bluescan && zsh'" \
           "bluesnarfer" "urxvt -e bash -c 'bluesnarfer -h && zsh'" \
           "braces" "urxvt -e bash -c 'braces -h && zsh'" \
           "bss" "urxvt -e bash -c 'bss -h && zsh'" \
           "psm_scan" "urxvt -e bash -c 'psm_scan -h && zsh'" \
           "rfcomm_scan" "urxvt -e bash -c 'rfcomm_scan -h && zsh'" \
           "btscanner" "urxvt -e bash -c 'btscanner --help && zsh'" \
           "carwhisperer" "urxvt -e bash -c 'carwhisperer -h && zsh'" \
           "crackle" "urxvt -e bash -c 'crackle && zsh'" \
           "fl0p" "urxvt -e bash -c 'fl0p -h && zsh'" \
           "ghettotooth" "urxvt -e bash -c 'ghettotooth && zsh'" \
           "hidattack" "urxvt -e bash -c 'hidattack -h && zsh'" \
           "obexstress" "urxvt -e bash -c 'obexstress -h && zsh'" \
           "redfang" "urxvt -e bash -c 'redfang --help && zsh'" \
           "spooftooph" "urxvt -e bash -c 'spooftooph -h && zsh'" \
           "tanya" "urxvt -e bash -c 'tanya && zsh'" \
           "tbear" "urxvt -e bash -c 'tbear -h && zsh'" \
           "tbsearch" "urxvt -e bash -c 'tbsearch && zsh'" \
           "ubertooth-btle" "urxvt -e bash -c 'ubertooth-btle -h && zsh'" \
           "ubertooth-dump" "urxvt -e bash -c 'ubertooth-dump -h && zsh'" \
           "ubertooth-follow" "urxvt -e bash -c 'ubertooth-follow -h && zsh'" \
           "ubertooth-hop" "urxvt -e bash -c 'ubertooth-hop -h && zsh'" \
           "ubertooth-lap" "urxvt -e bash -c 'ubertooth-lap -h && zsh'" \
           "ubertooth-specan" "urxvt -e bash -c 'ubertooth-specan -h && zsh'" \
           "ubertooth-uap" "urxvt -e bash -c 'ubertooth-uap -h && zsh'" \
           "ubertooth-util" "urxvt -e bash -c 'ubertooth-util -h && zsh'" \
