#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "database" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "sqlcheck" "urxvt -e bash -c 'sqlcheck -h && zsh'" \
           "sqldata" "urxvt -e bash -c 'sqldata -h && zsh'" \
           "getsids" "urxvt -e bash -c 'getsids && zsh'" \
           "metacoretex" "urxvt -e bash -c 'metacoretex && zsh'" \
           "mysql2sqlite" "urxvt -e bash -c 'mysql2sqlite -h && zsh'" \
           "pgdbf" "urxvt -e bash -c 'pgdbf -h && zsh'" \

