#!/usr/bin/bash

# Launch config files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load system specific things
~/.custom

# Get internet
sudo safeconnect

# give cursor
xsetroot -cursor_name left_ptr 

# Background
~/.tools/wp change &
~/bin/panel

# Init clipboard
~/.tools/clipboard init

# Keyboard bindings
xcape -t 300 -e 'Shift_L=parenleft;Shift_R=parenright;Hyper_L=Shift_L|exclam;Hyper_R=Shift_L|question' &
xset r 64
xset r 133
xset r rate 170 60
xset m 0 0 
xset -b

# Launch locking program
xautolock -detectsleep -locker '~/.tools/lock' -time 11 -corners 0-00 &

# Load xterm colors
xrdb -merge ~/.Xresources
xrdb -merge ~/.Xdefaults

# Start some programs
~/bin/offline-run &

# Automount
udiskie -N &

ratpoison
