#!/usr/bin/bash

# Launch config files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load system specific things
~/.custom.sh

# give cursor
xsetroot -cursor_name left_ptr 

# An2linux
#~/bin/an2linux.py &
statnot ~/dotfiles/Panel/statnot/config &

# Background
feh --bg-fill "$(find ~/.wallpapers/ -type f | shuf -n 1)"

# Init clipboard
~/.tools/clipboard init

# Toutchpad config
xinput --set-prop 12 "libinput Natural Scrolling Enabled" 1
xinput --set-prop 12 "libinput Tapping Enabled" 1

# Keyboard bindings
xset r 64
xset r 133
xset r rate 170 60
xset m 0 0 
xset -b

# Launch locking program
#xautolock -detectsleep -locker '~/.tools/lock' -time 11 -corners 0-00 &

# Load xterm colors
xrdb -merge ~/.Xresources
xrdb -merge ~/.Xdefaults

# Automount
udiskie -N  -T -q --no-appindicator -a &

xrandr --dpi 161
#compton --daemon -D 3
ratpoison
