#!/bin/sh
{ find ~/ \( ! -regex '.*/\..*' \); find ~/ \( -regex '.*/\..*' \) ; } | grep -v 'dotfiles/vim/undodir' | sed 's/ /\\ /g'  | dmenu -i -l 20 -nb '#eee8d5' -nf '#657b83' | xargs urxvt -e rifle -p0
#find ~/ | sed 's/ /\\ /g' | dmenu -i -l 20 -nb '#eee8d5' -nf '#657b83' | xargs urxvt -e rifle -p0
exit 0
