#! /bin/sh
source ~/.config/bspwm/colors

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.50

bspc config focused_border_color $COLOR0
bspc config active_border_color $COLOR0
bspc config normal_border_color $COLOR11

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true
bspc config ignore_ewmh_focus      true

bspc rule -a Gimp desktop=^8 floating=on follow=on
bspc rule -a Inkscape desktop=^7 floating=on


bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII

