#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "automation" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
          "armitage" "urxvt -e bash -c 'armitage -h && zsh'" \
           "teamserver" "urxvt -e bash -c 'teamserver && zsh'" \
           "binex" "urxvt -e bash -c 'binex -h && zsh'" \
           "blueranger" "urxvt -e bash -c 'blueranger && zsh'" \
           "cewl" "urxvt -e bash -c 'cewl -h && zsh'" \
           "cewl-fab" "urxvt -e bash -c 'cewl-fab && zsh'" \
           "checksec" "urxvt -e bash -c 'checksec --help && zsh'" \
           "checksec" "urxvt -e bash -c 'checksec --help && zsh'" \
           "cisco-snmp-enumeration" "urxvt -e bash -c 'cisco-snmp-enumeration && zsh'" \
           "clusterd" "urxvt -e bash -c 'clusterd -h && zsh'" \
           "cmsmap" "urxvt -e bash -c 'cmsmap -h && zsh'" \
           "crunch" "urxvt -e bash -c 'crunch -h && zsh'" \
           "dumb0" "urxvt -e bash -c 'dumb0 -h && zsh'" \
           "easy-creds" "urxvt -e bash -c 'easy-creds && zsh'" \
           "easyda" "urxvt -e bash -c 'easyda && zsh'" \
           "faraday" "urxvt -e bash -c 'faraday && zsh'" \
           "delAllHost.py" "urxvt -e bash -c 'delAllHost.py && zsh'" \
           "delAllServiceClosed.py" "urxvt -e bash -c 'delAllServiceClosed.py && zsh'" \
           "fplugin" "urxvt -e bash -c 'fplugin && zsh'" \
           "getAllCreds.py" "urxvt -e bash -c 'getAllCreds.py && zsh'" \
           "getAllHosts.py" "urxvt -e bash -c 'getAllHosts.py && zsh'" \
           "getAllIps.py" "urxvt -e bash -c 'getAllIps.py && zsh'" \
           "getAllIpsInterfaces.py" "urxvt -e bash -c 'getAllIpsInterfaces.py && zsh'" \
           "getAllOs.py" "urxvt -e bash -c 'getAllOs.py && zsh'" \
           "getAllTelnet.py" "urxvt -e bash -c 'getAllTelnet.py && zsh'" \
           "getAllVnc.py" "urxvt -e bash -c 'getAllVnc.py && zsh'" \
           "getAllVulnsCSV.py" "urxvt -e bash -c 'getAllVulnsCSV.py && zsh'" \
           "getAllWebservers.py" "urxvt -e bash -c 'getAllWebservers.py && zsh'" \
           "fstealer" "urxvt -e bash -c 'fstealer -h && zsh'" \
           "gooscan" "urxvt -e bash -c 'gooscan -h && zsh'" \
           "hackersh" "urxvt -e bash -c 'hackersh -h && zsh'" \
           "intersect-create" "urxvt -e bash -c 'intersect-create && zsh'" \
           "inurlbr" "urxvt -e bash -c 'inurlbr -h && zsh'" \
           "unix-jboss-autopwn" "urxvt -e bash -c 'unix-jboss-autopwn && zsh'" \
           "win-jboss-autopwn" "urxvt -e bash -c 'win-jboss-autopwn && zsh'" \
           "linset" "urxvt -e bash -c 'linset && zsh'" \
           "maskprocessor" "urxvt -e bash -c 'maskprocessor -h && zsh'" \
           "mp64" "urxvt -e bash -c 'mp64 --help && zsh'" \
           "mitmap.sh" "urxvt -e bash -c 'mitmap.sh -h && zsh'" \
           "mutator" "urxvt -e bash -c 'mutator -h && zsh'" \
           "nfspy" "urxvt -e bash -c 'nfspy -h && zsh'" \
           "nfspysh" "urxvt -e bash -c 'nfspysh -h && zsh'" \
           "nfsshell" "urxvt -e bash -c 'nfsshell -h && zsh'" \
           "owtf" "urxvt -e bash -c 'owtf && zsh'" \
           "panoptic" "urxvt -e bash -c 'panoptic -h && zsh'" \
           "phemail" "urxvt -e bash -c 'phemail -h && zsh'" \
           "pmcma" "urxvt -e bash -c 'pmcma && zsh'" \
           "regeorg" "urxvt -e bash -c 'regeorg -h && zsh'" \
           "rsmangler" "urxvt -e bash -c 'rsmangler -h && zsh'" \
           "sakis3g" "urxvt -e bash -c 'sakis3g --help && zsh'" \
           "shellme" "urxvt -e bash -c 'shellme -h && zsh'" \
           "shodan" "urxvt -e bash -c 'shodan && zsh'" \
           "simple-ducky" "urxvt -e bash -c 'simple-ducky && zsh'" \
           "svcrack" "urxvt -e bash -c 'svcrack -h && zsh'" \
           "svcrash" "urxvt -e bash -c 'svcrash -h && zsh'" \
           "svmap" "urxvt -e bash -c 'svmap -h && zsh'" \
           "svreport" "urxvt -e bash -c 'svreport -h && zsh'" \
           "svwar" "urxvt -e bash -c 'svwar -h && zsh'" \
           "sn00p" "urxvt -e bash -c 'sn00p -h && zsh'" \
           "sploitctl" "urxvt -e bash -c 'sploitctl -H && zsh'" \
           "ssl-phuck3r" "urxvt -e bash -c 'ssl-phuck3r -h && zsh'" \
           "statsprocessor" "urxvt -e bash -c 'statsprocessor --help && zsh'" \
           "tiger" "urxvt -e bash -c 'tiger -h && zsh'" \
           "tlssled" "urxvt -e bash -c 'tlssled -h && zsh'" \
           "unix-privsc-check" "urxvt -e bash -c 'unix-privsc-check && zsh'" \
           "username-anarchy" "urxvt -e bash -c 'username-anarchy -h && zsh'" \
           "usernamer" "urxvt -e bash -c 'usernamer -h && zsh'" \
           "veil" "urxvt -e bash -c 'veil && zsh'" \
           "vlan-hopping" "urxvt -e bash -c 'vlan-hopping && zsh'" \
           "voiphopper" "urxvt -e bash -c 'voiphopper -h && zsh'" \
           "wikigen" "urxvt -e bash -c 'wikigen && zsh'" \
           "wnmap" "urxvt -e bash -c 'wnmap -h && zsh'" \
           "yinjector" "urxvt -e bash -c 'yinjector -h && zsh'" \
 
