#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "binary" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "afl-clang" "urxvt -e bash -c 'afl-clang && zsh'" \
           "afl-clang++" "urxvt -e bash -c 'afl-clang++ && zsh'" \
           "afl-cmin" "urxvt -e bash -c 'afl-cmin && zsh'" \
           "afl-fuzz" "urxvt -e bash -c 'afl-fuzz && zsh'" \
           "afl-g++" "urxvt -e bash -c 'afl-g++ && zsh'" \
           "afl-gcc" "urxvt -e bash -c 'afl-gcc && zsh'" \
           "afl-gotcpu" "urxvt -e bash -c 'afl-gotcpu && zsh'" \
           "afl-plot" "urxvt -e bash -c 'afl-plot && zsh'" \
           "afl-showmap" "urxvt -e bash -c 'afl-showmap && zsh'" \
           "afl-tmin" "urxvt -e bash -c 'afl-tmin && zsh'" \
           "afl-whatsup" "urxvt -e bash -c 'afl-whatsup && zsh'" \
           "androapkinfo" "urxvt -e bash -c 'androapkinfo && zsh'" \
           "androaxml" "urxvt -e bash -c 'androaxml && zsh'" \
           "androcsign" "urxvt -e bash -c 'androcsign && zsh'" \
           "androdd" "urxvt -e bash -c 'androdd && zsh'" \
           "androdiff" "urxvt -e bash -c 'androdiff && zsh'" \
           "androgexf" "urxvt -e bash -c 'androgexf && zsh'" \
           "androlyze" "urxvt -e bash -c 'androlyze && zsh'" \
           "andromercury" "urxvt -e bash -c 'andromercury && zsh'" \
           "androrisk" "urxvt -e bash -c 'androrisk && zsh'" \
           "androsign" "urxvt -e bash -c 'androsign && zsh'" \
           "androsim" "urxvt -e bash -c 'androsim && zsh'" \
           "androxgmml" "urxvt -e bash -c 'androxgmml && zsh'" \
           "apkviewer" "urxvt -e bash -c 'apkviewer -h && zsh'" \
           "backdoor-factory" "urxvt -e bash -c 'backdoor-factory -h && zsh'" \
           "bdf-proxy" "urxvt -e bash -c 'bdf-proxy && zsh'" \
           "binwalk" "urxvt -e bash -c 'binwalk && zsh'" \
           "binwally" "urxvt -e bash -c 'binwally -h && zsh'" \
           "bsdiff" "urxvt -e bash -c 'bsdiff && zsh'" \
           "bspatch" "urxvt -e bash -c 'bspatch && zsh'" \
           "bsdiff" "urxvt -e bash -c 'bsdiff && zsh'" \
           "bspatch" "urxvt -e bash -c 'bspatch && zsh'" \
           "bmore" "urxvt -e bash -c 'bmore && zsh'" \
           "bvedit" "urxvt -e bash -c 'bvedit -h && zsh'" \
           "bvi" "urxvt -e bash -c 'bvi -h && zsh'" \
           "bview" "urxvt -e bash -c 'bview -h && zsh'" \
           "bytecode-viewer" "urxvt -e bash -c 'bytecode-viewer && zsh'" \
           "damm" "urxvt -e bash -c 'damm -h && zsh'" \
           "detect-it-easy" "urxvt -e bash -c 'detect-it-easy && zsh'" \
           "dissector" "urxvt -e bash -c 'dissector -h && zsh'" \
           "haystack" "urxvt -e bash -c 'haystack -h && zsh'" \
           "haystack-dump" "urxvt -e bash -c 'haystack-dump -h && zsh'" \
           "haystack-gui" "urxvt -e bash -c 'haystack-gui && zsh'" \
           "haystack-reverse" "urxvt -e bash -c 'haystack-reverse -h && zsh'" \
           "hex2bin" "urxvt -e bash -c 'hex2bin && zsh'" \
           "mot2bin" "urxvt -e bash -c 'mot2bin && zsh'" \
           "imagejs" "urxvt -e bash -c 'imagejs && zsh'" \
           "jwscan" "urxvt -e bash -c 'jwscan -h && zsh'" \
           "melkor" "urxvt -e bash -c 'melkor -h && zsh'" \
           "ms-sys" "urxvt -e bash -c 'ms-sys -h && zsh'" \
           "msvpwn" "urxvt -e bash -c 'msvpwn -h && zsh'" \
           "ezhexviewer" "urxvt -e bash -c 'ezhexviewer && zsh'" \
           "olebrowse" "urxvt -e bash -c 'olebrowse && zsh'" \
           "oleid" "urxvt -e bash -c 'oleid -h && zsh'" \
           "olemeta" "urxvt -e bash -c 'olemeta -h && zsh'" \
           "oletimes" "urxvt -e bash -c 'oletimes && zsh'" \
           "olevba" "urxvt -e bash -c 'olevba && zsh'" \
           "pyxswf" "urxvt -e bash -c 'pyxswf && zsh'" \
           "rtfobj" "urxvt -e bash -c 'rtfobj && zsh'" \
           "pdf2graph" "urxvt -e bash -c 'pdf2graph && zsh'" \
           "pdf2pdfa" "urxvt -e bash -c 'pdf2pdfa && zsh'" \
           "pdf2ruby" "urxvt -e bash -c 'pdf2ruby && zsh'" \
           "pdfcocoon" "urxvt -e bash -c 'pdfcocoon && zsh'" \
           "pdfcop" "urxvt -e bash -c 'pdfcop && zsh'" \
           "pdfdecompress" "urxvt -e bash -c 'pdfdecompress && zsh'" \
           "pdfdecrypt" "urxvt -e bash -c 'pdfdecrypt && zsh'" \
           "pdfencrypt" "urxvt -e bash -c 'pdfencrypt && zsh'" \
           "pdfexplode" "urxvt -e bash -c 'pdfexplode && zsh'" \
           "pdfextract" "urxvt -e bash -c 'pdfextract && zsh'" \
           "pdfmetadata" "urxvt -e bash -c 'pdfmetadata && zsh'" \
           "pdfsh" "urxvt -e bash -c 'pdfsh && zsh'" \
           "pdfwalker" "urxvt -e bash -c 'pdfwalker && zsh'" \
           "pdf2graph" "urxvt -e bash -c 'pdf2graph && zsh'" \
           "pdf2pdfa" "urxvt -e bash -c 'pdf2pdfa && zsh'" \
           "pdf2ruby" "urxvt -e bash -c 'pdf2ruby && zsh'" \
           "pdfcocoon" "urxvt -e bash -c 'pdfcocoon && zsh'" \
           "pdfcop" "urxvt -e bash -c 'pdfcop && zsh'" \
           "pdfdecompress" "urxvt -e bash -c 'pdfdecompress && zsh'" \
           "pdfdecrypt" "urxvt -e bash -c 'pdfdecrypt && zsh'" \
           "pdfencrypt" "urxvt -e bash -c 'pdfencrypt && zsh'" \
           "pdfexplode" "urxvt -e bash -c 'pdfexplode && zsh'" \
           "pdfextract" "urxvt -e bash -c 'pdfextract && zsh'" \
           "pdfmetadata" "urxvt -e bash -c 'pdfmetadata && zsh'" \
           "pdfsh" "urxvt -e bash -c 'pdfsh && zsh'" \
           "pdfwalker" "urxvt -e bash -c 'pdfwalker && zsh'" \
           "packerid" "urxvt -e bash -c 'packerid -h && zsh'" \
           "peframe" "urxvt -e bash -c 'peframe && zsh'" \
           "ropgadget" "urxvt -e bash -c 'ropgadget && zsh'" \
           "soot" "urxvt -e bash -c 'soot -h && zsh'" \
           "trid" "urxvt -e bash -c 'trid -h && zsh'" \
           "upx" "urxvt -e bash -c 'upx -h && zsh'" \
           "upx" "urxvt -e bash -c 'upx -h && zsh'" \
           "callgrind_annotate" "urxvt -e bash -c 'callgrind_annotate && zsh'" \
           "callgrind_control" "urxvt -e bash -c 'callgrind_control && zsh'" \
           "cg_annotate" "urxvt -e bash -c 'cg_annotate && zsh'" \
           "cg_diff" "urxvt -e bash -c 'cg_diff && zsh'" \
           "cg_merge" "urxvt -e bash -c 'cg_merge && zsh'" \
           "ms_print" "urxvt -e bash -c 'ms_print && zsh'" \
           "valgrind" "urxvt -e bash -c 'valgrind && zsh'" \
           "valgrind-di-server" "urxvt -e bash -c 'valgrind-di-server && zsh'" \
           "valgrind-listener" "urxvt -e bash -c 'valgrind-listener && zsh'" \
           "vgdb" "urxvt -e bash -c 'vgdb && zsh'" \
           "callgrind_annotate" "urxvt -e bash -c 'callgrind_annotate && zsh'" \
           "callgrind_control" "urxvt -e bash -c 'callgrind_control && zsh'" \
           "cg_annotate" "urxvt -e bash -c 'cg_annotate && zsh'" \
           "cg_diff" "urxvt -e bash -c 'cg_diff && zsh'" \
           "cg_merge" "urxvt -e bash -c 'cg_merge && zsh'" \
           "ms_print" "urxvt -e bash -c 'ms_print && zsh'" \
           "valgrind" "urxvt -e bash -c 'valgrind && zsh'" \
           "valgrind-di-server" "urxvt -e bash -c 'valgrind-di-server && zsh'" \
           "valgrind-listener" "urxvt -e bash -c 'valgrind-listener && zsh'" \
           "vgdb" "urxvt -e bash -c 'vgdb && zsh'" \
           "viper" "urxvt -e bash -c 'viper -h && zsh'" \
