#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "cracker" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "acccheck" "urxvt -e bash -c 'acccheck -h && zsh'" \
           "aesfix" "urxvt -e bash -c 'aesfix && zsh'" \
           "aeskeyfind" "urxvt -e bash -c 'aeskeyfind -h && zsh'" \
           "against" "urxvt -e bash -c 'against && zsh'" \
           "asleap" "urxvt -e bash -c 'asleap -h && zsh'" \
           "genkeys" "urxvt -e bash -c 'genkeys -h && zsh'" \
           "balbuzard" "urxvt -e bash -c 'balbuzard && zsh'" \
           "bbcrack" "urxvt -e bash -c 'bbcrack && zsh'" \
           "bbharvest" "urxvt -e bash -c 'bbharvest && zsh'" \
           "bbtrans" "urxvt -e bash -c 'bbtrans && zsh'" \
           "beleth" "urxvt -e bash -c 'beleth -h && zsh'" \
           "bgp-md5crack" "urxvt -e bash -c 'bgp-md5crack -h && zsh'" \
           "pxedump" "urxvt -e bash -c 'pxedump -h && zsh'" \
           "usbdump" "urxvt -e bash -c 'usbdump -h && zsh'" \
           "bkhive" "urxvt -e bash -c 'bkhive -h && zsh'" \
           "bh" "urxvt -e bash -c 'bh && zsh'" \
           "blackhash" "urxvt -e bash -c 'blackhash && zsh'" \
           "bob_admin-sse2" "urxvt -e bash -c 'bob_admin-sse2 -h && zsh'" \
           "bob_client-sse2" "urxvt -e bash -c 'bob_client-sse2 -h && zsh'" \
           "bob_server-sse2" "urxvt -e bash -c 'bob_server-sse2 -h && zsh'" \
           "brutessh" "urxvt -e bash -c 'brutessh -h && zsh'" \
           "bully" "urxvt -e bash -c 'bully -h && zsh'" \
           "cewl" "urxvt -e bash -c 'cewl -h && zsh'" \
           "cewl-fab" "urxvt -e bash -c 'cewl-fab && zsh'" \
           "chapcrack" "urxvt -e bash -c 'chapcrack -h && zsh'" \
           "checkpwd" "urxvt -e bash -c 'checkpwd -h && zsh'" \
           "checkpwd_nopw" "urxvt -e bash -c 'checkpwd_nopw && zsh'" \
           "sqlplus" "urxvt -e bash -c 'sqlplus -h && zsh'" \
           "chntpw" "urxvt -e bash -c 'chntpw -h && zsh'" \
           "cpnt" "urxvt -e bash -c 'cpnt && zsh'" \
           "reged" "urxvt -e bash -c 'reged && zsh'" \
           "chntpw" "urxvt -e bash -c 'chntpw -h && zsh'" \
           "cpnt" "urxvt -e bash -c 'cpnt && zsh'" \
           "reged" "urxvt -e bash -c 'reged && zsh'" \
           "cintruder" "urxvt -e bash -c 'cintruder -h && zsh'" \
           "CAT" "urxvt -e bash -c 'CAT && zsh'" \
           "cisco-auditing-tool" "urxvt -e bash -c 'cisco-auditing-tool && zsh'" \
           "cisco-ocs" "urxvt -e bash -c 'cisco-ocs && zsh'" \
           "cisco-scanner" "urxvt -e bash -c 'cisco-scanner -h && zsh'" \
           "cisco-snmp-enumeration" "urxvt -e bash -c 'cisco-snmp-enumeration && zsh'" \
           "c5c" "urxvt -e bash -c 'c5c --help && zsh'" \
           "cisco7crack" "urxvt -e bash -c 'cisco7crack -h && zsh'" \
           "cmospwd" "urxvt -e bash -c 'cmospwd -h && zsh'" \
           "cowpatty" "urxvt -e bash -c 'cowpatty -h && zsh'" \
           "genpmk" "urxvt -e bash -c 'genpmk -h && zsh'" \
           "crackhor" "urxvt -e bash -c 'crackhor -h && zsh'" \
           "crackle" "urxvt -e bash -c 'crackle && zsh'" \
           "crack-standalone" "urxvt -e bash -c 'crack-standalone -h && zsh'" \
           "crackclient" "urxvt -e bash -c 'crackclient -h && zsh'" \
           "crackserver" "urxvt -e bash -c 'crackserver -h && zsh'" \
           "crowbar" "urxvt -e bash -c 'crowbar --help && zsh'" \
           "crunch" "urxvt -e bash -c 'crunch -h && zsh'" \
           "cupp" "urxvt -e bash -c 'cupp && zsh'" \
           "dbpwaudit" "urxvt -e bash -c 'dbpwaudit -h && zsh'" \
           "DBPwAudit.jar" "urxvt -e bash -c 'DBPwAudit.jar && zsh'" \
           "delldrac" "urxvt -e bash -c 'delldrac -h && zsh'" \
           "depant" "urxvt -e bash -c 'depant && zsh'" \
           "device-pharmer" "urxvt -e bash -c 'device-pharmer -h && zsh'" \
           "dislocker" "urxvt -e bash -c 'dislocker -h && zsh'" \
           "dpeparser" "urxvt -e bash -c 'dpeparser -h && zsh'" \
           "eapmd5pass" "urxvt -e bash -c 'eapmd5pass && zsh'" \
           "enabler" "urxvt -e bash -c 'enabler && zsh'" \
           "facebrute" "urxvt -e bash -c 'facebrute -h && zsh'" \
           "fang" "urxvt -e bash -c 'fang -h && zsh'" \
           "fcrackzip" "urxvt -e bash -c 'fcrackzip --help && zsh'" \
           "fzipinfo" "urxvt -e bash -c 'fzipinfo --help && zsh'" \
           "fcrackzip" "urxvt -e bash -c 'fcrackzip --help && zsh'" \
           "fzipinfo" "urxvt -e bash -c 'fzipinfo --help && zsh'" \
           "fern" "urxvt -e bash -c 'fern && zsh'" \
           "findmyhash" "urxvt -e bash -c 'findmyhash -h && zsh'" \
           "findmyhash" "urxvt -e bash -c 'findmyhash -h && zsh'" \
           "ftp-scanner" "urxvt -e bash -c 'ftp-scanner -h && zsh'" \
           "ftp-spider" "urxvt -e bash -c 'ftp-spider -h && zsh'" \
           "hashcat" "urxvt -e bash -c 'hashcat && zsh'" \
           "hashcat-cleanup-rules" "urxvt -e bash -c 'hashcat-cleanup-rules && zsh'" \
           "hashcat-combinator" "urxvt -e bash -c 'hashcat-combinator && zsh'" \
           "hashcat-combinator3" "urxvt -e bash -c 'hashcat-combinator3 && zsh'" \
           "hashcat-combipow" "urxvt -e bash -c 'hashcat-combipow && zsh'" \
           "hashcat-cutb" "urxvt -e bash -c 'hashcat-cutb && zsh'" \
           "hashcat-expander" "urxvt -e bash -c 'hashcat-expander -h && zsh'" \
           "hashcat-gate" "urxvt -e bash -c 'hashcat-gate && zsh'" \
           "hashcat-generate-rules" "urxvt -e bash -c 'hashcat-generate-rules && zsh'" \
           "hashcat-hcstatgen" "urxvt -e bash -c 'hashcat-hcstatgen && zsh'" \
           "hashcat-keyspace" "urxvt -e bash -c 'hashcat-keyspace && zsh'" \
           "hashcat-len" "urxvt -e bash -c 'hashcat-len && zsh'" \
           "hashcat-mli2" "urxvt -e bash -c 'hashcat-mli2 && zsh'" \
           "hashcat-morph" "urxvt -e bash -c 'hashcat-morph && zsh'" \
           "hashcat-permute" "urxvt -e bash -c 'hashcat-permute -h && zsh'" \
           "hashcat-permute_exist" "urxvt -e bash -c 'hashcat-permute_exist && zsh'" \
           "hashcat-prepare" "urxvt -e bash -c 'hashcat-prepare -h && zsh'" \
           "hashcat-req-exclude" "urxvt -e bash -c 'hashcat-req-exclude && zsh'" \
           "hashcat-req-include" "urxvt -e bash -c 'hashcat-req-include && zsh'" \
           "hashcat-rli" "urxvt -e bash -c 'hashcat-rli && zsh'" \
           "hashcat-rli2" "urxvt -e bash -c 'hashcat-rli2 && zsh'" \
           "hashcat-splitlen" "urxvt -e bash -c 'hashcat-splitlen && zsh'" \
           "hashcat-strip-bsn" "urxvt -e bash -c 'hashcat-strip-bsn && zsh'" \
           "hashcat-strip-bsr" "urxvt -e bash -c 'hashcat-strip-bsr && zsh'" \
           "hasher" "urxvt -e bash -c 'hasher -h && zsh'" \
           "hashpump" "urxvt -e bash -c 'hashpump -h && zsh'" \
           "hashtag" "urxvt -e bash -c 'hashtag -h && zsh'" \
           "hdcp-genkey" "urxvt -e bash -c 'hdcp-genkey && zsh'" \
           "hdmi-sniff" "urxvt -e bash -c 'hdmi-sniff -h && zsh'" \
           "hostbox-ssh" "urxvt -e bash -c 'hostbox-ssh -h && zsh'" \
           "dpl4hydra.sh" "urxvt -e bash -c 'dpl4hydra.sh -h && zsh'" \
           "hydra" "urxvt -e bash -c 'hydra -h && zsh'" \
           "hydra-wizard.sh" "urxvt -e bash -c 'hydra-wizard.sh && zsh'" \
           "pw-inspector" "urxvt -e bash -c 'pw-inspector -h && zsh'" \
           "iax-scan-hosts" "urxvt -e bash -c 'iax-scan-hosts -h && zsh'" \
           "iax-scan-users" "urxvt -e bash -c 'iax-scan-users -h && zsh'" \
           "ibrute" "urxvt -e bash -c 'ibrute -h && zsh'" \
           "iheartxor" "urxvt -e bash -c 'iheartxor && zsh'" \
           "iisbf" "urxvt -e bash -c 'iisbf && zsh'" \
           "ikecrack-snarf-1.00.pl" "urxvt -e bash -c 'ikecrack-snarf-1.00.pl && zsh'" \
           "inguma" "urxvt -e bash -c 'inguma -h && zsh'" \
           "inguma" "urxvt -e bash -c 'inguma -h && zsh'" \
           "ingumagui" "urxvt -e bash -c 'ingumagui && zsh'" \
           "interrogate" "urxvt -e bash -c 'interrogate -h && zsh'" \
           "jbrute" "urxvt -e bash -c 'jbrute --help && zsh'" \
           "calc_stat" "urxvt -e bash -c 'calc_stat && zsh'" \
           "genmkvpwd" "urxvt -e bash -c 'genmkvpwd && zsh'" \
           "hccap2john" "urxvt -e bash -c 'hccap2john && zsh'" \
           "john" "urxvt -e bash -c 'john && zsh'" \
           "john-mailer" "urxvt -e bash -c 'john-mailer && zsh'" \
           "keepass2john" "urxvt -e bash -c 'keepass2john && zsh'" \
           "mkvcalcproba" "urxvt -e bash -c 'mkvcalcproba && zsh'" \
           "pdf2john" "urxvt -e bash -c 'pdf2john && zsh'" \
           "pwsafe2john" "urxvt -e bash -c 'pwsafe2john && zsh'" \
           "racf2john" "urxvt -e bash -c 'racf2john && zsh'" \
           "rar2john" "urxvt -e bash -c 'rar2john && zsh'" \
           "raw2dyna" "urxvt -e bash -c 'raw2dyna && zsh'" \
           "relbench" "urxvt -e bash -c 'relbench && zsh'" \
           "ssh2john" "urxvt -e bash -c 'ssh2john && zsh'" \
           "tgtsnarf" "urxvt -e bash -c 'tgtsnarf && zsh'" \
           "unafs" "urxvt -e bash -c 'unafs && zsh'" \
           "undrop" "urxvt -e bash -c 'undrop && zsh'" \
           "unique" "urxvt -e bash -c 'unique && zsh'" \
           "unshadow" "urxvt -e bash -c 'unshadow && zsh'" \
           "zip2john" "urxvt -e bash -c 'zip2john && zsh'" \
           "calc_stat" "urxvt -e bash -c 'calc_stat && zsh'" \
           "genmkvpwd" "urxvt -e bash -c 'genmkvpwd && zsh'" \
           "hccap2john" "urxvt -e bash -c 'hccap2john && zsh'" \
           "john" "urxvt -e bash -c 'john && zsh'" \
           "john-mailer" "urxvt -e bash -c 'john-mailer && zsh'" \
           "keepass2john" "urxvt -e bash -c 'keepass2john && zsh'" \
           "mkvcalcproba" "urxvt -e bash -c 'mkvcalcproba && zsh'" \
           "pdf2john" "urxvt -e bash -c 'pdf2john && zsh'" \
           "pwsafe2john" "urxvt -e bash -c 'pwsafe2john && zsh'" \
           "racf2john" "urxvt -e bash -c 'racf2john && zsh'" \
           "rar2john" "urxvt -e bash -c 'rar2john && zsh'" \
           "raw2dyna" "urxvt -e bash -c 'raw2dyna && zsh'" \
           "relbench" "urxvt -e bash -c 'relbench && zsh'" \
           "ssh2john" "urxvt -e bash -c 'ssh2john && zsh'" \
           "tgtsnarf" "urxvt -e bash -c 'tgtsnarf && zsh'" \
           "unafs" "urxvt -e bash -c 'unafs && zsh'" \
           "undrop" "urxvt -e bash -c 'undrop && zsh'" \
           "unique" "urxvt -e bash -c 'unique && zsh'" \
           "unshadow" "urxvt -e bash -c 'unshadow && zsh'" \
           "zip2john" "urxvt -e bash -c 'zip2john && zsh'" \
           "johnny" "urxvt -e bash -c 'johnny && zsh'" \
           "keimpx" "urxvt -e bash -c 'keimpx -h && zsh'" \
           "khc" "urxvt -e bash -c 'khc && zsh'" \
           "ldap-brute" "urxvt -e bash -c 'ldap-brute -h && zsh'" \
           "levye" "urxvt -e bash -c 'levye -h && zsh'" \
           "linset" "urxvt -e bash -c 'linset && zsh'" \
           "lodowep" "urxvt -e bash -c 'lodowep -h && zsh'" \
           "masscan" "urxvt -e bash -c 'masscan --help && zsh'" \
           "mdcrack" "urxvt -e bash -c 'mdcrack && zsh'" \
           "medusa" "urxvt -e bash -c 'medusa -h && zsh'" \
           "mfoc" "urxvt -e bash -c 'mfoc -h && zsh'" \
           "mkbrutus" "urxvt -e bash -c 'mkbrutus -h && zsh'" \
           "morxbook" "urxvt -e bash -c 'morxbook && zsh'" \
           "morxbrute" "urxvt -e bash -c 'morxbrute && zsh'" \
           "morxbtcrack" "urxvt -e bash -c 'morxbtcrack && zsh'" \
           "morxcoinpwn" "urxvt -e bash -c 'morxcoinpwn && zsh'" \
           "morxcrack" "urxvt -e bash -c 'morxcrack -h && zsh'" \
           "ncrack" "urxvt -e bash -c 'ncrack -h && zsh'" \
           "ncrack" "urxvt -e bash -c 'ncrack -h && zsh'" \
           "cudaHashcat" "urxvt -e bash -c 'cudaHashcat && zsh'" \
           "oclHashcat" "urxvt -e bash -c 'oclHashcat && zsh'" \
           "OCS" "urxvt -e bash -c 'OCS && zsh'" \
           "onesixtyone" "urxvt -e bash -c 'onesixtyone && zsh'" \
           "ophcrack" "urxvt -e bash -c 'ophcrack -h && zsh'" \
           "ophcrack" "urxvt -e bash -c 'ophcrack -h && zsh'" \
           "owabf" "urxvt -e bash -c 'owabf -h && zsh'" \
           "maskgen" "urxvt -e bash -c 'maskgen -h && zsh'" \
           "policygen" "urxvt -e bash -c 'policygen -h && zsh'" \
           "rulegen" "urxvt -e bash -c 'rulegen -h && zsh'" \
           "statsgen" "urxvt -e bash -c 'statsgen -h && zsh'" \
           "passcracking" "urxvt -e bash -c 'passcracking && zsh'" \
           "passe-partout" "urxvt -e bash -c 'passe-partout -h && zsh'" \
           "patator" "urxvt -e bash -c 'patator --help && zsh'" \
           "pdfcrack" "urxvt -e bash -c 'pdfcrack && zsh'" \
           "pdgmail" "urxvt -e bash -c 'pdgmail -h && zsh'" \
           "PHoss" "urxvt -e bash -c 'PHoss -h && zsh'" \
           "php_mt_seed" "urxvt -e bash -c 'php_mt_seed && zsh'" \
           "phrasendrescher" "urxvt -e bash -c 'phrasendrescher -h && zsh'" \
           "pipal" "urxvt -e bash -c 'pipal && zsh'" \
           "pyrit" "urxvt -e bash -c 'pyrit -h && zsh'" \
           "rcrack" "urxvt -e bash -c 'rcrack && zsh'" \
           "rtdump" "urxvt -e bash -c 'rtdump && zsh'" \
           "rtgen" "urxvt -e bash -c 'rtgen && zsh'" \
           "rtsort" "urxvt -e bash -c 'rtsort && zsh'" \
           "rarcrack" "urxvt -e bash -c 'rarcrack --help && zsh'" \
           "rcracki_mt" "urxvt -e bash -c 'rcracki_mt && zsh'" \
           "rdesktop-brute" "urxvt -e bash -c 'rdesktop-brute -h && zsh'" \
           "reaver" "urxvt -e bash -c 'reaver && zsh'" \
           "wash" "urxvt -e bash -c 'wash && zsh'" \
           "regeorg" "urxvt -e bash -c 'regeorg -h && zsh'" \
           "rid-enum" "urxvt -e bash -c 'rid-enum -h && zsh'" \
           "rlogin-scanner" "urxvt -e bash -c 'rlogin-scanner -h && zsh'" \
           "rootbrute" "urxvt -e bash -c 'rootbrute -h && zsh'" \
           "rpdscan" "urxvt -e bash -c 'rpdscan -h && zsh'" \
           "rsakeyfind" "urxvt -e bash -c 'rsakeyfind && zsh'" \
           "samdump2" "urxvt -e bash -c 'samdump2 && zsh'" \
           "samydeluxe" "urxvt -e bash -c 'samydeluxe -h && zsh'" \
           "sb0x" "urxvt -e bash -c 'sb0x -h && zsh'" \
           "sidguess" "urxvt -e bash -c 'sidguess && zsh'" \
           "sipcrack" "urxvt -e bash -c 'sipcrack -h && zsh'" \
           "sipdump" "urxvt -e bash -c 'sipdump -h && zsh'" \
           "nbdecode" "urxvt -e bash -c 'nbdecode && zsh'" \
           "smbbf" "urxvt -e bash -c 'smbbf -h && zsh'" \
           "smbdumpusers" "urxvt -e bash -c 'smbdumpusers && zsh'" \
           "smbgetserverinfo" "urxvt -e bash -c 'smbgetserverinfo && zsh'" \
           "snmpbrute" "urxvt -e bash -c 'snmpbrute && zsh'" \
           "sparta" "urxvt -e bash -c 'sparta && zsh'" \
           "speedport-arcadyan" "urxvt -e bash -c 'speedport-arcadyan && zsh'" \
           "speedpwn" "urxvt -e bash -c 'speedpwn -h && zsh'" \
           "sqlbf" "urxvt -e bash -c 'sqlbf && zsh'" \
           "ssh-privkey-crack" "urxvt -e bash -c 'ssh-privkey-crack && zsh'" \
           "sshatter" "urxvt -e bash -c 'sshatter && zsh'" \
           "sshscan" "urxvt -e bash -c 'sshscan -h && zsh'" \
           "sshtrix" "urxvt -e bash -c 'sshtrix -H && zsh'" \
           "sslnuke" "urxvt -e bash -c 'sslnuke && zsh'" \
           "sucrack" "urxvt -e bash -c 'sucrack && zsh'" \
           "tftpbrute" "urxvt -e bash -c 'tftpbrute && zsh'" \
           "keyfinder" "urxvt -e bash -c 'keyfinder && zsh'" \
           "thc-pptp-bruter" "urxvt -e bash -c 'thc-pptp-bruter && zsh'" \
           "thc-smartbrute" "urxvt -e bash -c 'thc-smartbrute -h && zsh'" \
           "ufo-wardriving" "urxvt -e bash -c 'ufo-wardriving && zsh'" \
           "VNC_bypauth" "urxvt -e bash -c 'VNC_bypauth && zsh'" \
           "vncrack" "urxvt -e bash -c 'vncrack && zsh'" \
           "wifite" "urxvt -e bash -c 'wifite && zsh'" \
           "wirouterkeyrec" "urxvt -e bash -c 'wirouterkeyrec && zsh'" \
           "wr_iwlist.sh" "urxvt -e bash -c 'wr_iwlist.sh && zsh'" \
           "wmat" "urxvt -e bash -c 'wmat && zsh'" \
           "wordbrutepress" "urxvt -e bash -c 'wordbrutepress && zsh'" \
           "wpbf" "urxvt -e bash -c 'wpbf -h && zsh'" \
           "wyd" "urxvt -e bash -c 'wyd && zsh'" \
           "xorbruteforcer" "urxvt -e bash -c 'xorbruteforcer && zsh'" \
           "zackattack" "urxvt -e bash -c 'zackattack -h && zsh'" \
           "zulu" "urxvt -e bash -c 'zulu && zsh'" \
           "zykeys" "urxvt -e bash -c 'zykeys && zsh'" \
