#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "hardware" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "arduino" "urxvt -e bash -c 'arduino -h && zsh'" \
           "avr-addr2line" "urxvt -e bash -c 'avr-addr2line -h && zsh'" \
           "avr-ar" "urxvt -e bash -c 'avr-ar -h && zsh'" \
           "avr-as" "urxvt -e bash -c 'avr-as -h && zsh'" \
           "avr-c++" "urxvt -e bash -c 'avr-c++ -h && zsh'" \
           "avr-c++filt" "urxvt -e bash -c 'avr-c++filt -h && zsh'" \
           "avr-cpp" "urxvt -e bash -c 'avr-cpp -h && zsh'" \
           "avr-g++" "urxvt -e bash -c 'avr-g++ -h && zsh'" \
           "avr-gcc" "urxvt -e bash -c 'avr-gcc -h && zsh'" \
           "avr-gcc-4.3.2" "urxvt -e bash -c 'avr-gcc-4.3.2 && zsh'" \
           "avr-gccbug" "urxvt -e bash -c 'avr-gccbug -h && zsh'" \
           "avr-ld" "urxvt -e bash -c 'avr-ld -h && zsh'" \
           "avr-nm" "urxvt -e bash -c 'avr-nm -h && zsh'" \
           "avr-objcopy" "urxvt -e bash -c 'avr-objcopy -h && zsh'" \
           "avr-objdump" "urxvt -e bash -c 'avr-objdump -h && zsh'" \
           "avr-ranlib" "urxvt -e bash -c 'avr-ranlib -h && zsh'" \
           "avr-size" "urxvt -e bash -c 'avr-size -h && zsh'" \
           "avr-strings" "urxvt -e bash -c 'avr-strings -h && zsh'" \
           "avr-strip" "urxvt -e bash -c 'avr-strip -h && zsh'" \
           "ar" "urxvt -e bash -c 'ar && zsh'" \
           "as" "urxvt -e bash -c 'as --help && zsh'" \
           "ld" "urxvt -e bash -c 'ld && zsh'" \
           "nm" "urxvt -e bash -c 'nm -h && zsh'" \
           "objcopy" "urxvt -e bash -c 'objcopy && zsh'" \
           "objdump" "urxvt -e bash -c 'objdump && zsh'" \
           "ranlib" "urxvt -e bash -c 'ranlib && zsh'" \
           "strip" "urxvt -e bash -c 'strip && zsh'" \
           "d2j-apk-sign" "urxvt -e bash -c 'd2j-apk-sign && zsh'" \
           "d2j-asm-verify" "urxvt -e bash -c 'd2j-asm-verify && zsh'" \
           "d2j-decrpyt-string" "urxvt -e bash -c 'd2j-decrpyt-string && zsh'" \
           "d2j-dex-asmifier" "urxvt -e bash -c 'd2j-dex-asmifier && zsh'" \
           "d2j-dex-dump" "urxvt -e bash -c 'd2j-dex-dump && zsh'" \
           "d2j-dex2jar" "urxvt -e bash -c 'd2j-dex2jar && zsh'" \
           "d2j-init-deobf" "urxvt -e bash -c 'd2j-init-deobf && zsh'" \
           "d2j-jar-access" "urxvt -e bash -c 'd2j-jar-access && zsh'" \
           "d2j-jar-remap" "urxvt -e bash -c 'd2j-jar-remap && zsh'" \
           "d2j-jar2dex" "urxvt -e bash -c 'd2j-jar2dex && zsh'" \
           "d2j-jar2jasmin" "urxvt -e bash -c 'd2j-jar2jasmin && zsh'" \
           "d2j-jasmin2jar" "urxvt -e bash -c 'd2j-jasmin2jar && zsh'" \
           "hdmi-sniff" "urxvt -e bash -c 'hdmi-sniff -h && zsh'" \
           "incept" "urxvt -e bash -c 'incept && zsh'" \
           "kautilya" "urxvt -e bash -c 'kautilya && zsh'" \
           "kraken" "urxvt -e bash -c 'kraken -h && zsh'" \
           "marc4dasm" "urxvt -e bash -c 'marc4dasm -h && zsh'" \
           "baksmali" "urxvt -e bash -c 'baksmali -h && zsh'" \
           "smali" "urxvt -e bash -c 'smali -h && zsh'" \
 
