#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "networking" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "afp_client" "urxvt -e bash -c 'afp_client && zsh'" \
           "afpcmd" "urxvt -e bash -c 'afpcmd -h && zsh'" \
           "afpfs" "urxvt -e bash -c 'afpfs && zsh'" \
           "afpfsd" "urxvt -e bash -c 'afpfsd -h && zsh'" \
           "afpgetstatus" "urxvt -e bash -c 'afpgetstatus && zsh'" \
           "mount_afp" "urxvt -e bash -c 'mount_afp && zsh'" \
           "afp_client" "urxvt -e bash -c 'afp_client && zsh'" \
           "afpcmd" "urxvt -e bash -c 'afpcmd -h && zsh'" \
           "afpfs" "urxvt -e bash -c 'afpfs && zsh'" \
           "afpfsd" "urxvt -e bash -c 'afpfsd -h && zsh'" \
           "afpgetstatus" "urxvt -e bash -c 'afpgetstatus && zsh'" \
           "mount_afp" "urxvt -e bash -c 'mount_afp && zsh'" \
           "aiengine" "urxvt -e bash -c 'aiengine -h && zsh'" \
           "argus" "urxvt -e bash -c 'argus -h && zsh'" \
           "argus-lsof" "urxvt -e bash -c 'argus-lsof && zsh'" \
           "argus-snmp" "urxvt -e bash -c 'argus-snmp && zsh'" \
           "argus-vmstat" "urxvt -e bash -c 'argus-vmstat && zsh'" \
           "argusbug" "urxvt -e bash -c 'argusbug && zsh'" \
           "argusclientbug" "urxvt -e bash -c 'argusclientbug && zsh'" \
           "ra" "urxvt -e bash -c 'ra -h && zsh'" \
           "rabins" "urxvt -e bash -c 'rabins -h && zsh'" \
           "racluster" "urxvt -e bash -c 'racluster -h && zsh'" \
           "raconvert" "urxvt -e bash -c 'raconvert -h && zsh'" \
           "racount" "urxvt -e bash -c 'racount -h && zsh'" \
           "radark" "urxvt -e bash -c 'radark -h && zsh'" \
           "radecode" "urxvt -e bash -c 'radecode && zsh'" \
           "radium" "urxvt -e bash -c 'radium -h && zsh'" \
           "radump" "urxvt -e bash -c 'radump && zsh'" \
           "raevent" "urxvt -e bash -c 'raevent -h && zsh'" \
           "rafilteraddr" "urxvt -e bash -c 'rafilteraddr && zsh'" \
           "ragraph" "urxvt -e bash -c 'ragraph && zsh'" \
           "ragrep" "urxvt -e bash -c 'ragrep && zsh'" \
           "rahisto" "urxvt -e bash -c 'rahisto && zsh'" \
           "rahosts" "urxvt -e bash -c 'rahosts && zsh'" \
           "ralabel" "urxvt -e bash -c 'ralabel && zsh'" \
           "ranonymize" "urxvt -e bash -c 'ranonymize && zsh'" \
           "rapath" "urxvt -e bash -c 'rapath && zsh'" \
           "rapolicy" "urxvt -e bash -c 'rapolicy && zsh'" \
           "raports" "urxvt -e bash -c 'raports && zsh'" \
           "rarpwatch" "urxvt -e bash -c 'rarpwatch && zsh'" \
           "raservices" "urxvt -e bash -c 'raservices && zsh'" \
           "rasort" "urxvt -e bash -c 'rasort -h && zsh'" \
           "rasplit" "urxvt -e bash -c 'rasplit -h && zsh'" \
           "rasql" "urxvt -e bash -c 'rasql -h && zsh'" \
           "rasqlinsert" "urxvt -e bash -c 'rasqlinsert && zsh'" \
           "rasqltimeindex" "urxvt -e bash -c 'rasqltimeindex && zsh'" \
           "rastream" "urxvt -e bash -c 'rastream -h && zsh'" \
           "rastrip" "urxvt -e bash -c 'rastrip -h && zsh'" \
           "ratemplate" "urxvt -e bash -c 'ratemplate && zsh'" \
           "ratimerange" "urxvt -e bash -c 'ratimerange && zsh'" \
           "ratop" "urxvt -e bash -c 'ratop && zsh'" \
           "rauserdata" "urxvt -e bash -c 'rauserdata && zsh'" \
           "arp-fingerprint" "urxvt -e bash -c 'arp-fingerprint -h && zsh'" \
           "arp-scan" "urxvt -e bash -c 'arp-scan -h && zsh'" \
           "get-iab" "urxvt -e bash -c 'get-iab -h && zsh'" \
           "get-oui" "urxvt -e bash -c 'get-oui -h && zsh'" \
           "arp-fingerprint" "urxvt -e bash -c 'arp-fingerprint -h && zsh'" \
           "arp-scan" "urxvt -e bash -c 'arp-scan -h && zsh'" \
           "get-iab" "urxvt -e bash -c 'get-iab -h && zsh'" \
           "get-oui" "urxvt -e bash -c 'get-oui -h && zsh'" \
           "arpwner" "urxvt -e bash -c 'arpwner -h && zsh'" \
           "backfuzz" "urxvt -e bash -c 'backfuzz -h && zsh'" \
           "bittwist" "urxvt -e bash -c 'bittwist -h && zsh'" \
           "bittwiste" "urxvt -e bash -c 'bittwiste -h && zsh'" \
           "buttinsky" "urxvt -e bash -c 'buttinsky -h && zsh'" \
           "cli" "urxvt -e bash -c 'cli && zsh'" \
           "netzobparse" "urxvt -e bash -c 'netzobparse && zsh'" \
           "spawner" "urxvt -e bash -c 'spawner && zsh'" \
           "stack" "urxvt -e bash -c 'stack && zsh'" \
           "cadaver" "urxvt -e bash -c 'cadaver -h && zsh'" \
           "cadaver" "urxvt -e bash -c 'cadaver -h && zsh'" \
           "chaosreader" "urxvt -e bash -c 'chaosreader -h && zsh'" \
           "chiron-combinations" "urxvt -e bash -c 'chiron-combinations && zsh'" \
           "chiron-nd" "urxvt -e bash -c 'chiron-nd && zsh'" \
           "chiron-proxy" "urxvt -e bash -c 'chiron-proxy && zsh'" \
           "chiron-scanner" "urxvt -e bash -c 'chiron-scanner && zsh'" \
           "chiron_combinations.py" "urxvt -e bash -c 'chiron_combinations.py && zsh'" \
           "chiron_local_link.py" "urxvt -e bash -c 'chiron_local_link.py && zsh'" \
           "chiron_proxy.py" "urxvt -e bash -c 'chiron_proxy.py && zsh'" \
           "chiron_scanner.py" "urxvt -e bash -c 'chiron_scanner.py && zsh'" \
           "cidr2range" "urxvt -e bash -c 'cidr2range -h && zsh'" \
           "cisco-snmp-enumeration" "urxvt -e bash -c 'cisco-snmp-enumeration && zsh'" \
           "cisco-snmp-slap" "urxvt -e bash -c 'cisco-snmp-slap -h && zsh'" \
           "darkstat" "urxvt -e bash -c 'darkstat -h && zsh'" \
           "darkstat" "urxvt -e bash -c 'darkstat -h && zsh'" \
           "depdep" "urxvt -e bash -c 'depdep -h && zsh'" \
           "dinouml" "urxvt -e bash -c 'dinouml -h && zsh'" \
           "dizzy" "urxvt -e bash -c 'dizzy -h && zsh'" \
           "dns-reverse-proxy" "urxvt -e bash -c 'dns-reverse-proxy -h && zsh'" \
           "dig" "urxvt -e bash -c 'dig -h && zsh'" \
           "host" "urxvt -e bash -c 'host && zsh'" \
           "nslookup" "urxvt -e bash -c 'nslookup && zsh'" \
           "dig" "urxvt -e bash -c 'dig -h && zsh'" \
           "host" "urxvt -e bash -c 'host && zsh'" \
           "nslookup" "urxvt -e bash -c 'nslookup && zsh'" \
           "arpspoof" "urxvt -e bash -c 'arpspoof && zsh'" \
           "dnsspoof" "urxvt -e bash -c 'dnsspoof -h && zsh'" \
           "dsniff" "urxvt -e bash -c 'dsniff -h && zsh'" \
           "filesnarf" "urxvt -e bash -c 'filesnarf -h && zsh'" \
           "macof" "urxvt -e bash -c 'macof -h && zsh'" \
           "mailsnarf" "urxvt -e bash -c 'mailsnarf -h && zsh'" \
           "msgsnarf" "urxvt -e bash -c 'msgsnarf -h && zsh'" \
           "sshmitm" "urxvt -e bash -c 'sshmitm -h && zsh'" \
           "sshow" "urxvt -e bash -c 'sshow -h && zsh'" \
           "tcpkill" "urxvt -e bash -c 'tcpkill -h && zsh'" \
           "tcpnice" "urxvt -e bash -c 'tcpnice -h && zsh'" \
           "urlsnarf" "urxvt -e bash -c 'urlsnarf -h && zsh'" \
           "webmitm" "urxvt -e bash -c 'webmitm -h && zsh'" \
           "webspy" "urxvt -e bash -c 'webspy -h && zsh'" \
           "arpspoof" "urxvt -e bash -c 'arpspoof && zsh'" \
           "dnsspoof" "urxvt -e bash -c 'dnsspoof -h && zsh'" \
           "dsniff" "urxvt -e bash -c 'dsniff -h && zsh'" \
           "filesnarf" "urxvt -e bash -c 'filesnarf -h && zsh'" \
           "macof" "urxvt -e bash -c 'macof -h && zsh'" \
           "mailsnarf" "urxvt -e bash -c 'mailsnarf -h && zsh'" \
           "msgsnarf" "urxvt -e bash -c 'msgsnarf -h && zsh'" \
           "sshmitm" "urxvt -e bash -c 'sshmitm -h && zsh'" \
           "sshow" "urxvt -e bash -c 'sshow -h && zsh'" \
           "tcpkill" "urxvt -e bash -c 'tcpkill -h && zsh'" \
           "tcpnice" "urxvt -e bash -c 'tcpnice -h && zsh'" \
           "urlsnarf" "urxvt -e bash -c 'urlsnarf -h && zsh'" \
           "webmitm" "urxvt -e bash -c 'webmitm -h && zsh'" \
           "webspy" "urxvt -e bash -c 'webspy -h && zsh'" \
           "dump1090" "urxvt -e bash -c 'dump1090 -h && zsh'" \
           "easy-creds" "urxvt -e bash -c 'easy-creds && zsh'" \
           "etherape" "urxvt -e bash -c 'etherape && zsh'" \
           "etherape" "urxvt -e bash -c 'etherape && zsh'" \
           "ettercap" "urxvt -e bash -c 'ettercap -h && zsh'" \
           "etterfilter" "urxvt -e bash -c 'etterfilter -h && zsh'" \
           "etterlog" "urxvt -e bash -c 'etterlog -h && zsh'" \
           "ettercap" "urxvt -e bash -c 'ettercap -h && zsh'" \
           "etterfilter" "urxvt -e bash -c 'etterfilter -h && zsh'" \
           "etterlog" "urxvt -e bash -c 'etterlog -h && zsh'" \
           "fakenetbiosdgm" "urxvt -e bash -c 'fakenetbiosdgm -h && zsh'" \
           "fakenetbiosns" "urxvt -e bash -c 'fakenetbiosns -h && zsh'" \
           "filibuster" "urxvt -e bash -c 'filibuster -h && zsh'" \
           "flowinspect" "urxvt -e bash -c 'flowinspect -h && zsh'" \
           "fping" "urxvt -e bash -c 'fping -h && zsh'" \
           "fping6" "urxvt -e bash -c 'fping6 -h && zsh'" \
           "fping" "urxvt -e bash -c 'fping -h && zsh'" \
           "fping6" "urxvt -e bash -c 'fping6 -h && zsh'" \
           "fraud-bridge" "urxvt -e bash -c 'fraud-bridge -h && zsh'" \
           "bmc-config" "urxvt -e bash -c 'bmc-config && zsh'" \
           "bmc-device" "urxvt -e bash -c 'bmc-device && zsh'" \
           "bmc-info" "urxvt -e bash -c 'bmc-info && zsh'" \
           "bmc-watchdog" "urxvt -e bash -c 'bmc-watchdog && zsh'" \
           "ipmi-chassis" "urxvt -e bash -c 'ipmi-chassis && zsh'" \
           "ipmi-chassis-config" "urxvt -e bash -c 'ipmi-chassis-config && zsh'" \
           "ipmi-config" "urxvt -e bash -c 'ipmi-config && zsh'" \
           "ipmi-console" "urxvt -e bash -c 'ipmi-console && zsh'" \
           "ipmi-dcmi" "urxvt -e bash -c 'ipmi-dcmi && zsh'" \
           "ipmi-detect" "urxvt -e bash -c 'ipmi-detect && zsh'" \
           "ipmi-fru" "urxvt -e bash -c 'ipmi-fru && zsh'" \
           "ipmi-locate" "urxvt -e bash -c 'ipmi-locate && zsh'" \
           "ipmi-oem" "urxvt -e bash -c 'ipmi-oem && zsh'" \
           "ipmi-pef-config" "urxvt -e bash -c 'ipmi-pef-config && zsh'" \
           "ipmi-pet" "urxvt -e bash -c 'ipmi-pet && zsh'" \
           "ipmi-ping" "urxvt -e bash -c 'ipmi-ping && zsh'" \
           "ipmi-power" "urxvt -e bash -c 'ipmi-power && zsh'" \
           "ipmi-raw" "urxvt -e bash -c 'ipmi-raw && zsh'" \
           "ipmi-sel" "urxvt -e bash -c 'ipmi-sel && zsh'" \
           "ipmi-sensors" "urxvt -e bash -c 'ipmi-sensors && zsh'" \
           "ipmi-sensors-config" "urxvt -e bash -c 'ipmi-sensors-config && zsh'" \
           "ipmiconsole" "urxvt -e bash -c 'ipmiconsole && zsh'" \
           "ipmidetect" "urxvt -e bash -c 'ipmidetect && zsh'" \
           "ipmidetectd" "urxvt -e bash -c 'ipmidetectd && zsh'" \
           "ipmimonitoring" "urxvt -e bash -c 'ipmimonitoring && zsh'" \
           "ipmiping" "urxvt -e bash -c 'ipmiping && zsh'" \
           "ipmipower" "urxvt -e bash -c 'ipmipower && zsh'" \
           "ipmiseld" "urxvt -e bash -c 'ipmiseld && zsh'" \
           "pef-config" "urxvt -e bash -c 'pef-config && zsh'" \
           "rmcp-ping" "urxvt -e bash -c 'rmcp-ping && zsh'" \
           "rmcpping" "urxvt -e bash -c 'rmcpping && zsh'" \
           "fs-nyarl" "urxvt -e bash -c 'fs-nyarl -h && zsh'" \
           "chaosreader0.94" "urxvt -e bash -c 'chaosreader0.94 && zsh'" \
           "geoiplookup" "urxvt -e bash -c 'geoiplookup && zsh'" \
           "geoiplookup6" "urxvt -e bash -c 'geoiplookup6 && zsh'" \
           "geoiplookup" "urxvt -e bash -c 'geoiplookup && zsh'" \
           "geoiplookup6" "urxvt -e bash -c 'geoiplookup6 && zsh'" \
           "gtp-scan" "urxvt -e bash -c 'gtp-scan -h && zsh'" \
           "gwcheck" "urxvt -e bash -c 'gwcheck -h && zsh'" \
           "hharp" "urxvt -e bash -c 'hharp -h && zsh'" \
           "hpfeeds-client" "urxvt -e bash -c 'hpfeeds-client -h && zsh'" \
           "hping" "urxvt -e bash -c 'hping --help && zsh'" \
           "hping2" "urxvt -e bash -c 'hping2 --help && zsh'" \
           "hping3" "urxvt -e bash -c 'hping3 --help && zsh'" \
           "hping" "urxvt -e bash -c 'hping --help && zsh'" \
           "hping2" "urxvt -e bash -c 'hping2 --help && zsh'" \
           "hping3" "urxvt -e bash -c 'hping3 --help && zsh'" \
           "http-traceroute" "urxvt -e bash -c 'http-traceroute -h && zsh'" \
           "httping" "urxvt -e bash -c 'httping --help && zsh'" \
           "hyenae" "urxvt -e bash -c 'hyenae --help && zsh'" \
           "hyenaed" "urxvt -e bash -c 'hyenaed --help && zsh'" \
           "idswakeup" "urxvt -e bash -c 'idswakeup -h && zsh'" \
           "ip-https-test" "urxvt -e bash -c 'ip-https-test && zsh'" \
           "ipaudit" "urxvt -e bash -c 'ipaudit && zsh'" \
           "ipstrings" "urxvt -e bash -c 'ipstrings && zsh'" \
           "stamp-h1" "urxvt -e bash -c 'stamp-h1 && zsh'" \
           "total" "urxvt -e bash -c 'total && zsh'" \
           "ipdecap" "urxvt -e bash -c 'ipdecap -h && zsh'" \
           "arping" "urxvt -e bash -c 'arping -h && zsh'" \
           "clockdiff" "urxvt -e bash -c 'clockdiff && zsh'" \
           "ping" "urxvt -e bash -c 'ping && zsh'" \
           "ping6" "urxvt -e bash -c 'ping6 && zsh'" \
           "rarpd" "urxvt -e bash -c 'rarpd && zsh'" \
           "rdisc" "urxvt -e bash -c 'rdisc && zsh'" \
           "tftpd" "urxvt -e bash -c 'tftpd && zsh'" \
           "tracepath" "urxvt -e bash -c 'tracepath -h && zsh'" \
           "tracepath6" "urxvt -e bash -c 'tracepath6 -h && zsh'" \
           "arping" "urxvt -e bash -c 'arping -h && zsh'" \
           "clockdiff" "urxvt -e bash -c 'clockdiff && zsh'" \
           "ping" "urxvt -e bash -c 'ping && zsh'" \
           "ping6" "urxvt -e bash -c 'ping6 && zsh'" \
           "rarpd" "urxvt -e bash -c 'rarpd && zsh'" \
           "rdisc" "urxvt -e bash -c 'rdisc && zsh'" \
           "tftpd" "urxvt -e bash -c 'tftpd && zsh'" \
           "tracepath" "urxvt -e bash -c 'tracepath -h && zsh'" \
           "tracepath6" "urxvt -e bash -c 'tracepath6 -h && zsh'" \
           "jnetmap" "urxvt -e bash -c 'jnetmap && zsh'" \
           "juncli" "urxvt -e bash -c 'juncli && zsh'" \
           "junkie" "urxvt -e bash -c 'junkie -h && zsh'" \
           "lans" "urxvt -e bash -c 'lans -h && zsh'" \
           "latcp" "urxvt -e bash -c 'latcp && zsh'" \
           "latd" "urxvt -e bash -c 'latd -h && zsh'" \
           "llogin" "urxvt -e bash -c 'llogin -h && zsh'" \
           "moprc" "urxvt -e bash -c 'moprc && zsh'" \
           "lft" "urxvt -e bash -c 'lft && zsh'" \
           "whob" "urxvt -e bash -c 'whob && zsh'" \
           "loki" "urxvt -e bash -c 'loki && zsh'" \
           "mpls_tunnel" "urxvt -e bash -c 'mpls_tunnel && zsh'" \
           "macchanger" "urxvt -e bash -c 'macchanger --help && zsh'" \
           "macchanger" "urxvt -e bash -c 'macchanger --help && zsh'" \
           "maclookup" "urxvt -e bash -c 'maclookup -h && zsh'" \
           "mz" "urxvt -e bash -c 'mz -h && zsh'" \
           "msfbinscan" "urxvt -e bash -c 'msfbinscan -h && zsh'" \
           "msfcli" "urxvt -e bash -c 'msfcli -h && zsh'" \
           "msfconsole" "urxvt -e bash -c 'msfconsole -h && zsh'" \
           "msfd" "urxvt -e bash -c 'msfd -h && zsh'" \
           "msfelfscan" "urxvt -e bash -c 'msfelfscan -h && zsh'" \
           "msfencode" "urxvt -e bash -c 'msfencode -h && zsh'" \
           "msfmachscan" "urxvt -e bash -c 'msfmachscan -h && zsh'" \
           "msfpayload" "urxvt -e bash -c 'msfpayload -h && zsh'" \
           "msfpescan" "urxvt -e bash -c 'msfpescan -h && zsh'" \
           "msfrop" "urxvt -e bash -c 'msfrop -h && zsh'" \
           "msfrpc" "urxvt -e bash -c 'msfrpc -h && zsh'" \
           "msfrpcd" "urxvt -e bash -c 'msfrpcd -h && zsh'" \
           "msfupdate" "urxvt -e bash -c 'msfupdate -h && zsh'" \
           "msfvenom" "urxvt -e bash -c 'msfvenom -h && zsh'" \
           "stager_reverse_https.bin" "urxvt -e bash -c 'stager_reverse_https.bin && zsh'" \
           "stty" "urxvt -e bash -c 'stty && zsh'" \
           "meterssh-monitor" "urxvt -e bash -c 'meterssh-monitor && zsh'" \
           "middler" "urxvt -e bash -c 'middler -h && zsh'" \
           "miredo" "urxvt -e bash -c 'miredo -h && zsh'" \
           "miredo-checkconf" "urxvt -e bash -c 'miredo-checkconf -h && zsh'" \
           "miredo-server" "urxvt -e bash -c 'miredo-server -h && zsh'" \
           "teredo-mire" "urxvt -e bash -c 'teredo-mire -h && zsh'" \
           "miredo" "urxvt -e bash -c 'miredo -h && zsh'" \
           "miredo-checkconf" "urxvt -e bash -c 'miredo-checkconf -h && zsh'" \
           "miredo-server" "urxvt -e bash -c 'miredo-server -h && zsh'" \
           "teredo-mire" "urxvt -e bash -c 'teredo-mire -h && zsh'" \
           "mitmer" "urxvt -e bash -c 'mitmer -h && zsh'" \
           "mitmf" "urxvt -e bash -c 'mitmf -h && zsh'" \
           "moloch-capture" "urxvt -e bash -c 'moloch-capture -h && zsh'" \
           "jade.js" "urxvt -e bash -c 'jade.js && zsh'" \
           "uglifyjs" "urxvt -e bash -c 'uglifyjs && zsh'" \
           "uglifyjs" "urxvt -e bash -c 'uglifyjs && zsh'" \
           "uglifyjs" "urxvt -e bash -c 'uglifyjs && zsh'" \
           "stylus" "urxvt -e bash -c 'stylus && zsh'" \
           "monocle" "urxvt -e bash -c 'monocle -h && zsh'" \
           "morxtunnel" "urxvt -e bash -c 'morxtunnel -h && zsh'" \
           "mptcp" "urxvt -e bash -c 'mptcp -h && zsh'" \
           "mptcp-fragmenter" "urxvt -e bash -c 'mptcp-fragmenter && zsh'" \
           "mptcp-scanner" "urxvt -e bash -c 'mptcp-scanner && zsh'" \
           "mtr" "urxvt -e bash -c 'mtr -h && zsh'" \
           "mtr" "urxvt -e bash -c 'mtr -h && zsh'" \
           "nacker" "urxvt -e bash -c 'nacker -h && zsh'" \
           "dnscat" "urxvt -e bash -c 'dnscat -h && zsh'" \
           "dnslogger" "urxvt -e bash -c 'dnslogger -h && zsh'" \
           "dnstest" "urxvt -e bash -c 'dnstest -h && zsh'" \
           "dnsxss" "urxvt -e bash -c 'dnsxss -h && zsh'" \
           "nbquery" "urxvt -e bash -c 'nbquery -h && zsh'" \
           "nbsniff" "urxvt -e bash -c 'nbsniff -h && zsh'" \
           "ipx_cmd" "urxvt -e bash -c 'ipx_cmd && zsh'" \
           "ipx_configure" "urxvt -e bash -c 'ipx_configure && zsh'" \
           "ipx_interface" "urxvt -e bash -c 'ipx_interface && zsh'" \
           "ipx_internal_net" "urxvt -e bash -c 'ipx_internal_net && zsh'" \
           "ipx_route" "urxvt -e bash -c 'ipx_route && zsh'" \
           "ncopy" "urxvt -e bash -c 'ncopy && zsh'" \
           "ncplogin" "urxvt -e bash -c 'ncplogin -h && zsh'" \
           "ncplogout" "urxvt -e bash -c 'ncplogout -h && zsh'" \
           "ncpmap" "urxvt -e bash -c 'ncpmap -h && zsh'" \
           "ncpmount" "urxvt -e bash -c 'ncpmount -h && zsh'" \
           "ncpumount" "urxvt -e bash -c 'ncpumount -h && zsh'" \
           "nprint" "urxvt -e bash -c 'nprint -h && zsh'" \
           "nsend" "urxvt -e bash -c 'nsend && zsh'" \
           "nwauth" "urxvt -e bash -c 'nwauth -h && zsh'" \
           "nwbocreate" "urxvt -e bash -c 'nwbocreate -h && zsh'" \
           "nwbols" "urxvt -e bash -c 'nwbols -h && zsh'" \
           "nwboprops" "urxvt -e bash -c 'nwboprops -h && zsh'" \
           "nwborm" "urxvt -e bash -c 'nwborm -h && zsh'" \
           "nwbpadd" "urxvt -e bash -c 'nwbpadd -h && zsh'" \
           "nwbpcreate" "urxvt -e bash -c 'nwbpcreate && zsh'" \
           "nwbprm" "urxvt -e bash -c 'nwbprm -h && zsh'" \
           "nwbpset" "urxvt -e bash -c 'nwbpset -h && zsh'" \
           "nwbpvalues" "urxvt -e bash -c 'nwbpvalues -h && zsh'" \
           "nwdir" "urxvt -e bash -c 'nwdir -h && zsh'" \
           "nwdpvalues" "urxvt -e bash -c 'nwdpvalues -h && zsh'" \
           "nwfsctrl" "urxvt -e bash -c 'nwfsctrl -h && zsh'" \
           "nwfsinfo" "urxvt -e bash -c 'nwfsinfo -h && zsh'" \
           "nwfstime" "urxvt -e bash -c 'nwfstime -h && zsh'" \
           "nwgrant" "urxvt -e bash -c 'nwgrant && zsh'" \
           "nwmsg" "urxvt -e bash -c 'nwmsg -h && zsh'" \
           "nwpasswd" "urxvt -e bash -c 'nwpasswd -h && zsh'" \
           "nwpjmv" "urxvt -e bash -c 'nwpjmv -h && zsh'" \
           "nwpqjob" "urxvt -e bash -c 'nwpqjob -h && zsh'" \
           "nwpurge" "urxvt -e bash -c 'nwpurge -h && zsh'" \
           "nwrevoke" "urxvt -e bash -c 'nwrevoke -h && zsh'" \
           "nwrights" "urxvt -e bash -c 'nwrights -h && zsh'" \
           "nwsfind" "urxvt -e bash -c 'nwsfind -h && zsh'" \
           "nwtrustee" "urxvt -e bash -c 'nwtrustee -h && zsh'" \
           "nwtrustee2" "urxvt -e bash -c 'nwtrustee2 -h && zsh'" \
           "nwuserlist" "urxvt -e bash -c 'nwuserlist -h && zsh'" \
           "nwvolinfo" "urxvt -e bash -c 'nwvolinfo -h && zsh'" \
           "pqlist" "urxvt -e bash -c 'pqlist && zsh'" \
           "pqrm" "urxvt -e bash -c 'pqrm && zsh'" \
           "pqstat" "urxvt -e bash -c 'pqstat && zsh'" \
           "pserver" "urxvt -e bash -c 'pserver -h && zsh'" \
           "slist" "urxvt -e bash -c 'slist && zsh'" \
           "nemesis" "urxvt -e bash -c 'nemesis -h && zsh'" \
           "nemesis" "urxvt -e bash -c 'nemesis -h && zsh'" \
           "netcmd" "urxvt -e bash -c 'netcmd -h && zsh'" \
           "netcon" "urxvt -e bash -c 'netcon -H && zsh'" \
           "makelist" "urxvt -e bash -c 'makelist -h && zsh'" \
           "netmap" "urxvt -e bash -c 'netmap -h && zsh'" \
           "ndecode" "urxvt -e bash -c 'ndecode && zsh'" \
           "nlist" "urxvt -e bash -c 'nlist && zsh'" \
           "nstrobe" "urxvt -e bash -c 'nstrobe && zsh'" \
           "ntrace" "urxvt -e bash -c 'ntrace && zsh'" \
           "ntraf" "urxvt -e bash -c 'ntraf -h && zsh'" \
           "netscan" "urxvt -e bash -c 'netscan -h && zsh'" \
           "netsed" "urxvt -e bash -c 'netsed -h && zsh'" \
           "netzob" "urxvt -e bash -c 'netzob -h && zsh'" \
           "nfex" "urxvt -e bash -c 'nfex -h && zsh'" \
           "nfsshell" "urxvt -e bash -c 'nfsshell -h && zsh'" \
           "ngrep" "urxvt -e bash -c 'ngrep -h && zsh'" \
           "ngrep" "urxvt -e bash -c 'ngrep -h && zsh'" \
           "nield" "urxvt -e bash -c 'nield -h && zsh'" \
           "nipper" "urxvt -e bash -c 'nipper --help && zsh'" \
           "nkiller2" "urxvt -e bash -c 'nkiller2 -h && zsh'" \
           "nsdtool" "urxvt -e bash -c 'nsdtool && zsh'" \
           "nsoq" "urxvt -e bash -c 'nsoq && zsh'" \
           "obfsproxy" "urxvt -e bash -c 'obfsproxy -h && zsh'" \
           "opensvp" "urxvt -e bash -c 'opensvp -h && zsh'" \
           "drone" "urxvt -e bash -c 'drone && zsh'" \
           "ostinato" "urxvt -e bash -c 'ostinato -h && zsh'" \
           "packet-o-matic" "urxvt -e bash -c 'packet-o-matic -h && zsh'" \
           "packETH" "urxvt -e bash -c 'packETH && zsh'" \
           "packETH" "urxvt -e bash -c 'packETH && zsh'" \
           "packit" "urxvt -e bash -c 'packit && zsh'" \
           "pacumen_classify_pcap.py" "urxvt -e bash -c 'pacumen_classify_pcap.py && zsh'" \
           "pacumen_timeseries.py" "urxvt -e bash -c 'pacumen_timeseries.py && zsh'" \
           "pacumen_train.py" "urxvt -e bash -c 'pacumen_train.py && zsh'" \
           "pacumen_visualize.py" "urxvt -e bash -c 'pacumen_visualize.py && zsh'" \
           "train_all.py" "urxvt -e bash -c 'train_all.py && zsh'" \
           "xval.py" "urxvt -e bash -c 'xval.py && zsh'" \
           "pcapfix" "urxvt -e bash -c 'pcapfix && zsh'" \
           "plcscan" "urxvt -e bash -c 'plcscan -h && zsh'" \
           "prometheus" "urxvt -e bash -c 'prometheus -h && zsh'" \
           "ptunnel" "urxvt -e bash -c 'ptunnel -h && zsh'" \
           "pwnat" "urxvt -e bash -c 'pwnat -h && zsh'" \
           "pyminifakedns" "urxvt -e bash -c 'pyminifakedns && zsh'" \
           "dhcp-responder" "urxvt -e bash -c 'dhcp-responder -h && zsh'" \
           "responder" "urxvt -e bash -c 'responder -h && zsh'" \
           "rinetd" "urxvt -e bash -c 'rinetd -h && zsh'" \
           "rtpbreak" "urxvt -e bash -c 'rtpbreak -h && zsh'" \
           "sbd" "urxvt -e bash -c 'sbd -h && zsh'" \
           "UTscapy" "urxvt -e bash -c 'UTscapy -h && zsh'" \
           "scapy" "urxvt -e bash -c 'scapy -h && zsh'" \
           "UTscapy" "urxvt -e bash -c 'UTscapy -h && zsh'" \
           "scapy" "urxvt -e bash -c 'scapy -h && zsh'" \
           "sessionlist" "urxvt -e bash -c 'sessionlist && zsh'" \
           "flowcap" "urxvt -e bash -c 'flowcap && zsh'" \
           "mapsid" "urxvt -e bash -c 'mapsid && zsh'" \
           "num2dot" "urxvt -e bash -c 'num2dot && zsh'" \
           "rwaddrcount" "urxvt -e bash -c 'rwaddrcount && zsh'" \
           "rwallformats" "urxvt -e bash -c 'rwallformats && zsh'" \
           "rwappend" "urxvt -e bash -c 'rwappend && zsh'" \
           "rwbag" "urxvt -e bash -c 'rwbag && zsh'" \
           "rwbagbuild" "urxvt -e bash -c 'rwbagbuild && zsh'" \
           "rwbagcat" "urxvt -e bash -c 'rwbagcat && zsh'" \
           "rwbagtool" "urxvt -e bash -c 'rwbagtool && zsh'" \
           "rwcat" "urxvt -e bash -c 'rwcat && zsh'" \
           "rwcombine" "urxvt -e bash -c 'rwcombine && zsh'" \
           "rwcompare" "urxvt -e bash -c 'rwcompare && zsh'" \
           "rwcount" "urxvt -e bash -c 'rwcount && zsh'" \
           "rwcut" "urxvt -e bash -c 'rwcut && zsh'" \
           "rwdedupe" "urxvt -e bash -c 'rwdedupe && zsh'" \
           "rwfglob" "urxvt -e bash -c 'rwfglob && zsh'" \
           "rwfileinfo" "urxvt -e bash -c 'rwfileinfo && zsh'" \
           "rwfilter" "urxvt -e bash -c 'rwfilter && zsh'" \
           "rwflowappend" "urxvt -e bash -c 'rwflowappend && zsh'" \
           "rwflowpack" "urxvt -e bash -c 'rwflowpack && zsh'" \
           "rwgeoip2ccmap" "urxvt -e bash -c 'rwgeoip2ccmap && zsh'" \
           "rwgroup" "urxvt -e bash -c 'rwgroup && zsh'" \
           "rwguess" "urxvt -e bash -c 'rwguess && zsh'" \
           "rwip2cc" "urxvt -e bash -c 'rwip2cc && zsh'" \
           "rwmatch" "urxvt -e bash -c 'rwmatch && zsh'" \
           "rwnetmask" "urxvt -e bash -c 'rwnetmask && zsh'" \
           "rwpackchecker" "urxvt -e bash -c 'rwpackchecker && zsh'" \
           "rwpdu2silk" "urxvt -e bash -c 'rwpdu2silk && zsh'" \
           "rwpmapbuild" "urxvt -e bash -c 'rwpmapbuild && zsh'" \
           "rwpmapcat" "urxvt -e bash -c 'rwpmapcat && zsh'" \
           "rwpmaplookup" "urxvt -e bash -c 'rwpmaplookup && zsh'" \
           "rwrandomizeip" "urxvt -e bash -c 'rwrandomizeip && zsh'" \
           "rwreceiver" "urxvt -e bash -c 'rwreceiver && zsh'" \
           "rwrecgenerator" "urxvt -e bash -c 'rwrecgenerator && zsh'" \
           "rwresolve" "urxvt -e bash -c 'rwresolve && zsh'" \
           "rwrtd2split" "urxvt -e bash -c 'rwrtd2split && zsh'" \
           "rwscan" "urxvt -e bash -c 'rwscan && zsh'" \
           "rwscanquery" "urxvt -e bash -c 'rwscanquery && zsh'" \
           "rwsender" "urxvt -e bash -c 'rwsender && zsh'" \
           "rwset" "urxvt -e bash -c 'rwset && zsh'" \
           "rwsetbuild" "urxvt -e bash -c 'rwsetbuild && zsh'" \
           "rwsetcat" "urxvt -e bash -c 'rwsetcat && zsh'" \
           "rwsetmember" "urxvt -e bash -c 'rwsetmember && zsh'" \
           "rwsettool" "urxvt -e bash -c 'rwsettool && zsh'" \
           "rwsiteinfo" "urxvt -e bash -c 'rwsiteinfo && zsh'" \
           "rwsort" "urxvt -e bash -c 'rwsort && zsh'" \
           "rwsplit" "urxvt -e bash -c 'rwsplit && zsh'" \
           "rwstats" "urxvt -e bash -c 'rwstats && zsh'" \
           "rwswapbytes" "urxvt -e bash -c 'rwswapbytes && zsh'" \
           "rwtotal" "urxvt -e bash -c 'rwtotal && zsh'" \
           "rwtuc" "urxvt -e bash -c 'rwtuc && zsh'" \
           "rwuniq" "urxvt -e bash -c 'rwuniq && zsh'" \
           "silk_config" "urxvt -e bash -c 'silk_config && zsh'" \
           "simple-lan-scan" "urxvt -e bash -c 'simple-lan-scan -h && zsh'" \
           "sn00p" "urxvt -e bash -c 'sn00p -h && zsh'" \
           "sj-commit-results" "urxvt -e bash -c 'sj-commit-results -h && zsh'" \
           "sj-iptcpopt-probe" "urxvt -e bash -c 'sj-iptcpopt-probe -h && zsh'" \
           "sniffjoke" "urxvt -e bash -c 'sniffjoke -h && zsh'" \
           "sniffjoke-autotest" "urxvt -e bash -c 'sniffjoke-autotest -h && zsh'" \
           "sniffjokectl" "urxvt -e bash -c 'sniffjokectl -h && zsh'" \
           "snmpbrute" "urxvt -e bash -c 'snmpbrute && zsh'" \
           "snmpfuzz" "urxvt -e bash -c 'snmpfuzz && zsh'" \
           "snmpattack" "urxvt -e bash -c 'snmpattack -h && zsh'" \
           "snmpcheck-nothink" "urxvt -e bash -c 'snmpcheck-nothink -h && zsh'" \
           "snort" "urxvt -e bash -c 'snort -h && zsh'" \
           "u2boat" "urxvt -e bash -c 'u2boat && zsh'" \
           "u2spewfoo" "urxvt -e bash -c 'u2spewfoo && zsh'" \
           "filan" "urxvt -e bash -c 'filan -h && zsh'" \
           "procan" "urxvt -e bash -c 'procan -h && zsh'" \
           "socat" "urxvt -e bash -c 'socat -h && zsh'" \
           "filan" "urxvt -e bash -c 'filan -h && zsh'" \
           "procan" "urxvt -e bash -c 'procan -h && zsh'" \
           "socat" "urxvt -e bash -c 'socat -h && zsh'" \
           "sockstat" "urxvt -e bash -c 'sockstat -h && zsh'" \
           "sparta" "urxvt -e bash -c 'sparta && zsh'" \
           "spipe" "urxvt -e bash -c 'spipe && zsh'" \
           "spiped" "urxvt -e bash -c 'spiped && zsh'" \
           "sps" "urxvt -e bash -c 'sps -h && zsh'" \
           "ssdp-scanner" "urxvt -e bash -c 'ssdp-scanner && zsh'" \
           "sshuttle" "urxvt -e bash -c 'sshuttle -h && zsh'" \
           "sshuttle" "urxvt -e bash -c 'sshuttle -h && zsh'" \
           "ssl-phuck3r" "urxvt -e bash -c 'ssl-phuck3r -h && zsh'" \
           "sslh" "urxvt -e bash -c 'sslh -h && zsh'" \
           "sslh-fork" "urxvt -e bash -c 'sslh-fork -h && zsh'" \
           "sslh-select" "urxvt -e bash -c 'sslh-select -h && zsh'" \
           "sslh" "urxvt -e bash -c 'sslh -h && zsh'" \
           "sslh-fork" "urxvt -e bash -c 'sslh-fork -h && zsh'" \
           "sslh-select" "urxvt -e bash -c 'sslh-select -h && zsh'" \
           "sslsplit" "urxvt -e bash -c 'sslsplit -h && zsh'" \
           "sslstrip" "urxvt -e bash -c 'sslstrip -h && zsh'" \
           "mitm_listener" "urxvt -e bash -c 'mitm_listener && zsh'" \
           "stunnel" "urxvt -e bash -c 'stunnel && zsh'" \
           "stunnel3" "urxvt -e bash -c 'stunnel3 && zsh'" \
           "stunnel" "urxvt -e bash -c 'stunnel && zsh'" \
           "stunnel3" "urxvt -e bash -c 'stunnel3 && zsh'" \
           "swaks" "urxvt -e bash -c 'swaks --help && zsh'" \
           "swaks" "urxvt -e bash -c 'swaks --help && zsh'" \
           "t50" "urxvt -e bash -c 't50 --help && zsh'" \
           "tcpcontrol-fuzzer.pl" "urxvt -e bash -c 'tcpcontrol-fuzzer.pl && zsh'" \
           "tcpdump" "urxvt -e bash -c 'tcpdump -h && zsh'" \
           "tcpdump" "urxvt -e bash -c 'tcpdump -h && zsh'" \
           "tcpextract" "urxvt -e bash -c 'tcpextract -h && zsh'" \
           "tcpflow" "urxvt -e bash -c 'tcpflow -h && zsh'" \
           "tcpflow" "urxvt -e bash -c 'tcpflow -h && zsh'" \
           "tcpbridge" "urxvt -e bash -c 'tcpbridge -h && zsh'" \
           "tcpcapinfo" "urxvt -e bash -c 'tcpcapinfo && zsh'" \
           "tcpliveplay" "urxvt -e bash -c 'tcpliveplay && zsh'" \
           "tcpprep" "urxvt -e bash -c 'tcpprep -h && zsh'" \
           "tcpreplay" "urxvt -e bash -c 'tcpreplay -h && zsh'" \
           "tcpreplay-edit" "urxvt -e bash -c 'tcpreplay-edit && zsh'" \
           "tcprewrite" "urxvt -e bash -c 'tcprewrite -h && zsh'" \
           "tcpbridge" "urxvt -e bash -c 'tcpbridge -h && zsh'" \
           "tcpcapinfo" "urxvt -e bash -c 'tcpcapinfo && zsh'" \
           "tcpliveplay" "urxvt -e bash -c 'tcpliveplay && zsh'" \
           "tcpprep" "urxvt -e bash -c 'tcpprep -h && zsh'" \
           "tcpreplay" "urxvt -e bash -c 'tcpreplay -h && zsh'" \
           "tcpreplay-edit" "urxvt -e bash -c 'tcpreplay-edit && zsh'" \
           "tcprewrite" "urxvt -e bash -c 'tcprewrite -h && zsh'" \
           "tcptraceroute" "urxvt -e bash -c 'tcptraceroute && zsh'" \
           "tcpwatch" "urxvt -e bash -c 'tcpwatch && zsh'" \
           "tftp-proxy" "urxvt -e bash -c 'tftp-proxy -h && zsh'" \
           "6to4test.sh" "urxvt -e bash -c '6to4test.sh && zsh'" \
           "address6" "urxvt -e bash -c 'address6 && zsh'" \
           "alive6" "urxvt -e bash -c 'alive6 && zsh'" \
           "covert_send6" "urxvt -e bash -c 'covert_send6 && zsh'" \
           "covert_send6d" "urxvt -e bash -c 'covert_send6d && zsh'" \
           "denial6" "urxvt -e bash -c 'denial6 && zsh'" \
           "detect-new-ip6" "urxvt -e bash -c 'detect-new-ip6 && zsh'" \
           "detect_sniffer6" "urxvt -e bash -c 'detect_sniffer6 && zsh'" \
           "dnsdict6" "urxvt -e bash -c 'dnsdict6 && zsh'" \
           "dnsrevenum6" "urxvt -e bash -c 'dnsrevenum6 && zsh'" \
           "dnssecwalk" "urxvt -e bash -c 'dnssecwalk && zsh'" \
           "dos-new-ip6" "urxvt -e bash -c 'dos-new-ip6 && zsh'" \
           "dos_mld.sh" "urxvt -e bash -c 'dos_mld.sh && zsh'" \
           "dump_dhcp6" "urxvt -e bash -c 'dump_dhcp6 -h && zsh'" \
           "dump_router6" "urxvt -e bash -c 'dump_router6 && zsh'" \
           "exploit6" "urxvt -e bash -c 'exploit6 && zsh'" \
           "extract_hosts6.sh" "urxvt -e bash -c 'extract_hosts6.sh && zsh'" \
           "extract_networks6.sh" "urxvt -e bash -c 'extract_networks6.sh && zsh'" \
           "fake_advertise6" "urxvt -e bash -c 'fake_advertise6 && zsh'" \
           "fake_dhcps6" "urxvt -e bash -c 'fake_dhcps6 && zsh'" \
           "fake_dns6d" "urxvt -e bash -c 'fake_dns6d && zsh'" \
           "fake_dnsupdate6" "urxvt -e bash -c 'fake_dnsupdate6 && zsh'" \
           "fake_mipv6" "urxvt -e bash -c 'fake_mipv6 && zsh'" \
           "fake_mld26" "urxvt -e bash -c 'fake_mld26 && zsh'" \
           "fake_mld6" "urxvt -e bash -c 'fake_mld6 && zsh'" \
           "fake_mldrouter6" "urxvt -e bash -c 'fake_mldrouter6 && zsh'" \
           "fake_pim6" "urxvt -e bash -c 'fake_pim6 && zsh'" \
           "fake_router26" "urxvt -e bash -c 'fake_router26 && zsh'" \
           "fake_router6" "urxvt -e bash -c 'fake_router6 && zsh'" \
           "fake_solicitate6" "urxvt -e bash -c 'fake_solicitate6 && zsh'" \
           "firewall6" "urxvt -e bash -c 'firewall6 && zsh'" \
           "flood_advertise6" "urxvt -e bash -c 'flood_advertise6 && zsh'" \
           "flood_dhcpc6" "urxvt -e bash -c 'flood_dhcpc6 && zsh'" \
           "flood_mld26" "urxvt -e bash -c 'flood_mld26 && zsh'" \
           "flood_mld6" "urxvt -e bash -c 'flood_mld6 && zsh'" \
           "flood_mldrouter6" "urxvt -e bash -c 'flood_mldrouter6 && zsh'" \
           "flood_redir6" "urxvt -e bash -c 'flood_redir6 && zsh'" \
           "flood_router26" "urxvt -e bash -c 'flood_router26 && zsh'" \
           "flood_router6" "urxvt -e bash -c 'flood_router6 && zsh'" \
           "flood_rs6" "urxvt -e bash -c 'flood_rs6 && zsh'" \
           "flood_solicitate6" "urxvt -e bash -c 'flood_solicitate6 && zsh'" \
           "four2six" "urxvt -e bash -c 'four2six && zsh'" \
           "fragmentation6" "urxvt -e bash -c 'fragmentation6 && zsh'" \
           "fuzz_dhcpc6" "urxvt -e bash -c 'fuzz_dhcpc6 && zsh'" \
           "fuzz_dhcpc6-usage.pdf" "urxvt -e bash -c 'fuzz_dhcpc6-usage.pdf && zsh'" \
           "fuzz_dhcps6" "urxvt -e bash -c 'fuzz_dhcps6 && zsh'" \
           "fuzz_ip6" "urxvt -e bash -c 'fuzz_ip6 && zsh'" \
           "grep6.pl" "urxvt -e bash -c 'grep6.pl && zsh'" \
           "implementation6" "urxvt -e bash -c 'implementation6 && zsh'" \
           "implementation6d" "urxvt -e bash -c 'implementation6d && zsh'" \
           "inject_alive6" "urxvt -e bash -c 'inject_alive6 && zsh'" \
           "inverse_lookup6" "urxvt -e bash -c 'inverse_lookup6 && zsh'" \
           "kill_router6" "urxvt -e bash -c 'kill_router6 && zsh'" \
           "ndpexhaust26" "urxvt -e bash -c 'ndpexhaust26 && zsh'" \
           "ndpexhaust6" "urxvt -e bash -c 'ndpexhaust6 && zsh'" \
           "node_query6" "urxvt -e bash -c 'node_query6 && zsh'" \
           "parasite6" "urxvt -e bash -c 'parasite6 && zsh'" \
           "passive_discovery6" "urxvt -e bash -c 'passive_discovery6 && zsh'" \
           "randicmp6" "urxvt -e bash -c 'randicmp6 && zsh'" \
           "redir6" "urxvt -e bash -c 'redir6 && zsh'" \
           "redirsniff6" "urxvt -e bash -c 'redirsniff6 && zsh'" \
           "rsmurf6" "urxvt -e bash -c 'rsmurf6 && zsh'" \
           "sendpees6" "urxvt -e bash -c 'sendpees6 && zsh'" \
           "sendpeesmp6" "urxvt -e bash -c 'sendpeesmp6 && zsh'" \
           "six2four.sh" "urxvt -e bash -c 'six2four.sh && zsh'" \
           "smurf6" "urxvt -e bash -c 'smurf6 && zsh'" \
           "thc-ipv6-setup.sh" "urxvt -e bash -c 'thc-ipv6-setup.sh && zsh'" \
           "thcping6" "urxvt -e bash -c 'thcping6 && zsh'" \
           "thcsyn6" "urxvt -e bash -c 'thcsyn6 && zsh'" \
           "toobig6" "urxvt -e bash -c 'toobig6 && zsh'" \
           "trace6" "urxvt -e bash -c 'trace6 && zsh'" \
           "tincd" "urxvt -e bash -c 'tincd && zsh'" \
           "tincd" "urxvt -e bash -c 'tincd && zsh'" \
           "topera" "urxvt -e bash -c 'topera -h && zsh'" \
           "tor" "urxvt -e bash -c 'tor -h && zsh'" \
           "tor-gencert" "urxvt -e bash -c 'tor-gencert && zsh'" \
           "tor-resolve" "urxvt -e bash -c 'tor-resolve && zsh'" \
           "torify" "urxvt -e bash -c 'torify -h && zsh'" \
           "tor" "urxvt -e bash -c 'tor -h && zsh'" \
           "tor-gencert" "urxvt -e bash -c 'tor-gencert && zsh'" \
           "tor-resolve" "urxvt -e bash -c 'tor-resolve && zsh'" \
           "torify" "urxvt -e bash -c 'torify -h && zsh'" \
           "tunna-proxy" "urxvt -e bash -c 'tunna-proxy && zsh'" \
           "tunna-webserver" "urxvt -e bash -c 'tunna-webserver && zsh'" \
           "udptunnel" "urxvt -e bash -c 'udptunnel -h && zsh'" \
           "umit" "urxvt -e bash -c 'umit -h && zsh'" \
           "umit_scheduler.py" "urxvt -e bash -c 'umit_scheduler.py && zsh'" \
           "uw-offish" "urxvt -e bash -c 'uw-offish -h && zsh'" \
           "vlan-hopping" "urxvt -e bash -c 'vlan-hopping && zsh'" \
           "websockify" "urxvt -e bash -c 'websockify -h && zsh'" \
           "capinfos" "urxvt -e bash -c 'capinfos -h && zsh'" \
           "captype" "urxvt -e bash -c 'captype && zsh'" \
           "dftest" "urxvt -e bash -c 'dftest && zsh'" \
           "dumpcap" "urxvt -e bash -c 'dumpcap && zsh'" \
           "editcap" "urxvt -e bash -c 'editcap && zsh'" \
           "mergecap" "urxvt -e bash -c 'mergecap -h && zsh'" \
           "randpkt" "urxvt -e bash -c 'randpkt && zsh'" \
           "rawshark" "urxvt -e bash -c 'rawshark && zsh'" \
           "reordercap" "urxvt -e bash -c 'reordercap && zsh'" \
           "text2pcap" "urxvt -e bash -c 'text2pcap && zsh'" \
           "tshark" "urxvt -e bash -c 'tshark -h && zsh'" \
           "capinfos" "urxvt -e bash -c 'capinfos -h && zsh'" \
           "captype" "urxvt -e bash -c 'captype && zsh'" \
           "dftest" "urxvt -e bash -c 'dftest && zsh'" \
           "dumpcap" "urxvt -e bash -c 'dumpcap && zsh'" \
           "editcap" "urxvt -e bash -c 'editcap && zsh'" \
           "mergecap" "urxvt -e bash -c 'mergecap -h && zsh'" \
           "randpkt" "urxvt -e bash -c 'randpkt && zsh'" \
           "rawshark" "urxvt -e bash -c 'rawshark && zsh'" \
           "reordercap" "urxvt -e bash -c 'reordercap && zsh'" \
           "text2pcap" "urxvt -e bash -c 'text2pcap && zsh'" \
           "tshark" "urxvt -e bash -c 'tshark -h && zsh'" \
           "wireshark" "urxvt -e bash -c 'wireshark && zsh'" \
           "wireshark" "urxvt -e bash -c 'wireshark && zsh'" \
           "wol-e" "urxvt -e bash -c 'wol-e -h && zsh'" \
           "yersinia" "urxvt -e bash -c 'yersinia --help && zsh'" \
           "zackattack" "urxvt -e bash -c 'zackattack -h && zsh'" \
           "zarp" "urxvt -e bash -c 'zarp -h && zsh'" \
