#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "proxy" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "3proxy" "urxvt -e bash -c '3proxy --help && zsh'" \
           "countersutil" "urxvt -e bash -c 'countersutil && zsh'" \
           "dighosts" "urxvt -e bash -c 'dighosts && zsh'" \
           "ftppr" "urxvt -e bash -c 'ftppr --help && zsh'" \
           "mycrypt" "urxvt -e bash -c 'mycrypt && zsh'" \
           "pop3p" "urxvt -e bash -c 'pop3p --help && zsh'" \
           "socks" "urxvt -e bash -c 'socks --help && zsh'" \
           "tcppm" "urxvt -e bash -c 'tcppm --help && zsh'" \
           "udppm" "urxvt -e bash -c 'udppm --help && zsh'" \
           "3proxy.key" "urxvt -e bash -c '3proxy.key && zsh'" \
           "3proxy.pem" "urxvt -e bash -c '3proxy.pem && zsh'" \
           "rus-koi8-r.3ps" "urxvt -e bash -c 'rus-koi8-r.3ps && zsh'" \
           "rus-win1251.3ps" "urxvt -e bash -c 'rus-win1251.3ps && zsh'" \
           "server.key" "urxvt -e bash -c 'server.key && zsh'" \
           "bdf-proxy" "urxvt -e bash -c 'bdf-proxy && zsh'" \
           "burpsuite" "urxvt -e bash -c 'burpsuite && zsh'" \
           "chiron-combinations" "urxvt -e bash -c 'chiron-combinations && zsh'" \
           "chiron-nd" "urxvt -e bash -c 'chiron-nd && zsh'" \
           "chiron-proxy" "urxvt -e bash -c 'chiron-proxy && zsh'" \
           "chiron-scanner" "urxvt -e bash -c 'chiron-scanner && zsh'" \
           "chiron_combinations.py" "urxvt -e bash -c 'chiron_combinations.py && zsh'" \
           "chiron_local_link.py" "urxvt -e bash -c 'chiron_local_link.py && zsh'" \
           "chiron_proxy.py" "urxvt -e bash -c 'chiron_proxy.py && zsh'" \
           "chiron_scanner.py" "urxvt -e bash -c 'chiron_scanner.py && zsh'" \
           "dns-reverse-proxy" "urxvt -e bash -c 'dns-reverse-proxy -h && zsh'" \
           "dnschef" "urxvt -e bash -c 'dnschef -h && zsh'" \
           "elite-proxy-finder" "urxvt -e bash -c 'elite-proxy-finder -h && zsh'" \
           "fakedns" "urxvt -e bash -c 'fakedns && zsh'" \
           "mitmf" "urxvt -e bash -c 'mitmf -h && zsh'" \
           "mitmdump" "urxvt -e bash -c 'mitmdump -h && zsh'" \
           "mitmproxy" "urxvt -e bash -c 'mitmproxy -h && zsh'" \
           "obfsproxy" "urxvt -e bash -c 'obfsproxy -h && zsh'" \
           "proxychains" "urxvt -e bash -c 'proxychains && zsh'" \
           "proxychains4" "urxvt -e bash -c 'proxychains4 && zsh'" \
           "proxychains" "urxvt -e bash -c 'proxychains && zsh'" \
           "proxychains4" "urxvt -e bash -c 'proxychains4 && zsh'" \
           "proxycheck" "urxvt -e bash -c 'proxycheck -h && zsh'" \
           "proxyp" "urxvt -e bash -c 'proxyp -h && zsh'" \
           "proxytunnel" "urxvt -e bash -c 'proxytunnel -h && zsh'" \
           "proxytunnel" "urxvt -e bash -c 'proxytunnel -h && zsh'" \
           "ratproxy" "urxvt -e bash -c 'ratproxy -h && zsh'" \
           "regeorg" "urxvt -e bash -c 'regeorg -h && zsh'" \
           "replayproxy" "urxvt -e bash -c 'replayproxy -h && zsh'" \
           "sergio-proxy" "urxvt -e bash -c 'sergio-proxy -h && zsh'" \
           "sshuttle" "urxvt -e bash -c 'sshuttle -h && zsh'" \
           "sshuttle" "urxvt -e bash -c 'sshuttle -h && zsh'" \
           "sslnuke" "urxvt -e bash -c 'sslnuke && zsh'" \
           "mitm_listener" "urxvt -e bash -c 'mitm_listener && zsh'" \
           "tftp-proxy" "urxvt -e bash -c 'tftp-proxy -h && zsh'" \
           "tinyproxy" "urxvt -e bash -c 'tinyproxy -h && zsh'" \
           "tinyproxy" "urxvt -e bash -c 'tinyproxy -h && zsh'" \
           "tor" "urxvt -e bash -c 'tor -h && zsh'" \
           "tor-gencert" "urxvt -e bash -c 'tor-gencert && zsh'" \
           "tor-resolve" "urxvt -e bash -c 'tor-resolve && zsh'" \
           "torify" "urxvt -e bash -c 'torify -h && zsh'" \
           "tor" "urxvt -e bash -c 'tor -h && zsh'" \
           "tor-gencert" "urxvt -e bash -c 'tor-gencert && zsh'" \
           "tor-resolve" "urxvt -e bash -c 'tor-resolve && zsh'" \
           "torify" "urxvt -e bash -c 'torify -h && zsh'" \
           "torsocks" "urxvt -e bash -c 'torsocks -h && zsh'" \
           "torsocks" "urxvt -e bash -c 'torsocks -h && zsh'" \
           "tunna-proxy" "urxvt -e bash -c 'tunna-proxy && zsh'" \
           "tunna-webserver" "urxvt -e bash -c 'tunna-webserver && zsh'" \
           "webscarab" "urxvt -e bash -c 'webscarab && zsh'" \
           "ycrawler" "urxvt -e bash -c 'ycrawler -h && zsh'" \

