#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "tunnel" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "chownat" "urxvt -e bash -c 'chownat -h && zsh'" \
           "ctunnel" "urxvt -e bash -c 'ctunnel -h && zsh'" \
           "dns2tcpc" "urxvt -e bash -c 'dns2tcpc && zsh'" \
           "dns2tcpd" "urxvt -e bash -c 'dns2tcpd && zsh'" \
           "fraud-bridge" "urxvt -e bash -c 'fraud-bridge -h && zsh'" \
           "htc" "urxvt -e bash -c 'htc --help && zsh'" \
           "hts" "urxvt -e bash -c 'hts --help && zsh'" \
           "htc" "urxvt -e bash -c 'htc --help && zsh'" \
           "hts" "urxvt -e bash -c 'hts --help && zsh'" \
           "icmptx" "urxvt -e bash -c 'icmptx && zsh'" \
           "iodine" "urxvt -e bash -c 'iodine && zsh'" \
           "iodined" "urxvt -e bash -c 'iodined && zsh'" \
           "iodine" "urxvt -e bash -c 'iodine && zsh'" \
           "iodined" "urxvt -e bash -c 'iodined && zsh'" \
           "ip-https-test" "urxvt -e bash -c 'ip-https-test && zsh'" \
           "matahari" "urxvt -e bash -c 'matahari && zsh'" \
           "morxtunnel" "urxvt -e bash -c 'morxtunnel -h && zsh'" \
           "multitun" "urxvt -e bash -c 'multitun && zsh'" \
           "packet-o-matic" "urxvt -e bash -c 'packet-o-matic -h && zsh'" \
           "proxytunnel" "urxvt -e bash -c 'proxytunnel -h && zsh'" \
           "proxytunnel" "urxvt -e bash -c 'proxytunnel -h && zsh'" \
           "ptunnel" "urxvt -e bash -c 'ptunnel -h && zsh'" \
           "stunnel" "urxvt -e bash -c 'stunnel && zsh'" \
           "stunnel3" "urxvt -e bash -c 'stunnel3 && zsh'" \
           "stunnel" "urxvt -e bash -c 'stunnel && zsh'" \
           "stunnel3" "urxvt -e bash -c 'stunnel3 && zsh'" \
           "tor" "urxvt -e bash -c 'tor -h && zsh'" \
           "tor-gencert" "urxvt -e bash -c 'tor-gencert && zsh'" \
           "tor-resolve" "urxvt -e bash -c 'tor-resolve && zsh'" \
           "torify" "urxvt -e bash -c 'torify -h && zsh'" \
           "tor" "urxvt -e bash -c 'tor -h && zsh'" \
           "tor-gencert" "urxvt -e bash -c 'tor-gencert && zsh'" \
           "tor-resolve" "urxvt -e bash -c 'tor-resolve && zsh'" \
           "torify" "urxvt -e bash -c 'torify -h && zsh'" \
           "tunna-proxy" "urxvt -e bash -c 'tunna-proxy && zsh'" \
           "tunna-webserver" "urxvt -e bash -c 'tunna-webserver && zsh'" \
           "udptunnel" "urxvt -e bash -c 'udptunnel -h && zsh'" \
           "vstt" "urxvt -e bash -c 'vstt -h && zsh'" \
           "vstt-reader" "urxvt -e bash -c 'vstt-reader && zsh'" \
           "vstt-s2f" "urxvt -e bash -c 'vstt-s2f && zsh'" \
 
