#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "code-audit" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "cflow" "urxvt -e bash -c 'cflow -h && zsh'" \
           "cppcheck" "urxvt -e bash -c 'cppcheck -h && zsh'" \
           "cppcheck-gui" "urxvt -e bash -c 'cppcheck-gui && zsh'" \
           "cppcheck-htmlreport" "urxvt -e bash -c 'cppcheck-htmlreport -h && zsh'" \
           "cppcheck" "urxvt -e bash -c 'cppcheck -h && zsh'" \
           "cppcheck-gui" "urxvt -e bash -c 'cppcheck-gui && zsh'" \
           "cppcheck-htmlreport" "urxvt -e bash -c 'cppcheck-htmlreport -h && zsh'" \
           "dscanner" "urxvt -e bash -c 'dscanner -h && zsh'" \
           "flawfinder" "urxvt -e bash -c 'flawfinder -h && zsh'" \
           "procyon" "urxvt -e bash -c 'procyon && zsh'" \
           "pscan" "urxvt -e bash -c 'pscan -h && zsh'" \
           "splint" "urxvt -e bash -c 'splint -h && zsh'" \
           "splint" "urxvt -e bash -c 'splint -h && zsh'" \
           "callgrind_annotate" "urxvt -e bash -c 'callgrind_annotate && zsh'" \
           "callgrind_control" "urxvt -e bash -c 'callgrind_control && zsh'" \
           "cg_annotate" "urxvt -e bash -c 'cg_annotate && zsh'" \
           "cg_diff" "urxvt -e bash -c 'cg_diff && zsh'" \
           "cg_merge" "urxvt -e bash -c 'cg_merge && zsh'" \
           "ms_print" "urxvt -e bash -c 'ms_print && zsh'" \
           "valgrind" "urxvt -e bash -c 'valgrind && zsh'" \
           "valgrind-di-server" "urxvt -e bash -c 'valgrind-di-server && zsh'" \
           "valgrind-listener" "urxvt -e bash -c 'valgrind-listener && zsh'" \
           "vgdb" "urxvt -e bash -c 'vgdb && zsh'" \
           "callgrind_annotate" "urxvt -e bash -c 'callgrind_annotate && zsh'" \
           "callgrind_control" "urxvt -e bash -c 'callgrind_control && zsh'" \
           "cg_annotate" "urxvt -e bash -c 'cg_annotate && zsh'" \
           "cg_diff" "urxvt -e bash -c 'cg_diff && zsh'" \
           "cg_merge" "urxvt -e bash -c 'cg_merge && zsh'" \
           "ms_print" "urxvt -e bash -c 'ms_print && zsh'" \
           "valgrind" "urxvt -e bash -c 'valgrind && zsh'" \
           "valgrind-di-server" "urxvt -e bash -c 'valgrind-di-server && zsh'" \
           "valgrind-listener" "urxvt -e bash -c 'valgrind-listener && zsh'" \
           "vgdb" "urxvt -e bash -c 'vgdb && zsh'" \
