#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "debugger" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "edb" "urxvt -e bash -c 'edb && zsh'" \
           "gcore" "urxvt -e bash -c 'gcore && zsh'" \
           "gdb" "urxvt -e bash -c 'gdb -h && zsh'" \
           "gdbserver" "urxvt -e bash -c 'gdbserver --help && zsh'" \
           "gcore" "urxvt -e bash -c 'gcore && zsh'" \
           "gdb" "urxvt -e bash -c 'gdb -h && zsh'" \
           "gdbserver" "urxvt -e bash -c 'gdbserver --help && zsh'" \
           "malwasm" "urxvt -e bash -c 'malwasm && zsh'" \
           "ollydbg" "urxvt -e bash -c 'ollydbg && zsh'" \
           "peda" "urxvt -e bash -c 'peda -h && zsh'" \
           "r2" "urxvt -e bash -c 'r2 -h && zsh'" \
           "r2agent" "urxvt -e bash -c 'r2agent -h && zsh'" \
           "rabin2" "urxvt -e bash -c 'rabin2 -h && zsh'" \
           "radare2" "urxvt -e bash -c 'radare2 -h && zsh'" \
           "radiff2" "urxvt -e bash -c 'radiff2 -h && zsh'" \
           "rafind2" "urxvt -e bash -c 'rafind2 -h && zsh'" \
           "ragg2" "urxvt -e bash -c 'ragg2 -h && zsh'" \
           "ragg2-cc" "urxvt -e bash -c 'ragg2-cc && zsh'" \
           "rahash2" "urxvt -e bash -c 'rahash2 -h && zsh'" \
           "rarun2" "urxvt -e bash -c 'rarun2 -h && zsh'" \
           "rasm2" "urxvt -e bash -c 'rasm2 -h && zsh'" \
           "rax2" "urxvt -e bash -c 'rax2 && zsh'" \
           "shellnoob" "urxvt -e bash -c 'shellnoob -h && zsh'" \
           "vdbbin" "urxvt -e bash -c 'vdbbin -h && zsh'" \
           "vivbin" "urxvt -e bash -c 'vivbin -h && zsh'" \
