#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "defensive" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "aiengine" "urxvt -e bash -c 'aiengine -h && zsh'" \
           "argus" "urxvt -e bash -c 'argus -h && zsh'" \
           "argus-lsof" "urxvt -e bash -c 'argus-lsof && zsh'" \
           "argus-snmp" "urxvt -e bash -c 'argus-snmp && zsh'" \
           "argus-vmstat" "urxvt -e bash -c 'argus-vmstat && zsh'" \
           "argusbug" "urxvt -e bash -c 'argusbug && zsh'" \
           "argusclientbug" "urxvt -e bash -c 'argusclientbug && zsh'" \
           "ra" "urxvt -e bash -c 'ra -h && zsh'" \
           "rabins" "urxvt -e bash -c 'rabins -h && zsh'" \
           "racluster" "urxvt -e bash -c 'racluster -h && zsh'" \
           "raconvert" "urxvt -e bash -c 'raconvert -h && zsh'" \
           "racount" "urxvt -e bash -c 'racount -h && zsh'" \
           "radark" "urxvt -e bash -c 'radark -h && zsh'" \
           "radecode" "urxvt -e bash -c 'radecode && zsh'" \
           "radium" "urxvt -e bash -c 'radium -h && zsh'" \
           "radump" "urxvt -e bash -c 'radump && zsh'" \
           "raevent" "urxvt -e bash -c 'raevent -h && zsh'" \
           "rafilteraddr" "urxvt -e bash -c 'rafilteraddr && zsh'" \
           "ragraph" "urxvt -e bash -c 'ragraph && zsh'" \
           "ragrep" "urxvt -e bash -c 'ragrep && zsh'" \
           "rahisto" "urxvt -e bash -c 'rahisto && zsh'" \
           "rahosts" "urxvt -e bash -c 'rahosts && zsh'" \
           "ralabel" "urxvt -e bash -c 'ralabel && zsh'" \
           "ranonymize" "urxvt -e bash -c 'ranonymize && zsh'" \
           "rapath" "urxvt -e bash -c 'rapath && zsh'" \
           "rapolicy" "urxvt -e bash -c 'rapolicy && zsh'" \
           "raports" "urxvt -e bash -c 'raports && zsh'" \
           "rarpwatch" "urxvt -e bash -c 'rarpwatch && zsh'" \
           "raservices" "urxvt -e bash -c 'raservices && zsh'" \
           "rasort" "urxvt -e bash -c 'rasort -h && zsh'" \
           "rasplit" "urxvt -e bash -c 'rasplit -h && zsh'" \
           "rasql" "urxvt -e bash -c 'rasql -h && zsh'" \
           "rasqlinsert" "urxvt -e bash -c 'rasqlinsert && zsh'" \
           "rasqltimeindex" "urxvt -e bash -c 'rasqltimeindex && zsh'" \
           "rastream" "urxvt -e bash -c 'rastream -h && zsh'" \
           "rastrip" "urxvt -e bash -c 'rastrip -h && zsh'" \
           "ratemplate" "urxvt -e bash -c 'ratemplate && zsh'" \
           "ratimerange" "urxvt -e bash -c 'ratimerange && zsh'" \
           "ratop" "urxvt -e bash -c 'ratop && zsh'" \
           "rauserdata" "urxvt -e bash -c 'rauserdata && zsh'" \
           "arpalert" "urxvt -e bash -c 'arpalert -h && zsh'" \
           "tool_code.sh" "urxvt -e bash -c 'tool_code.sh && zsh'" \
           "arpon" "urxvt -e bash -c 'arpon -h && zsh'" \
           "artillery" "urxvt -e bash -c 'artillery && zsh'" \
           "bamfbrute" "urxvt -e bash -c 'bamfbrute -h && zsh'" \
           "bamfdetect" "urxvt -e bash -c 'bamfdetect -h && zsh'" \
           "beholder" "urxvt -e bash -c 'beholder -h && zsh'" \
           "centry" "urxvt -e bash -c 'centry -h && zsh'" \
           "chkrootkit" "urxvt -e bash -c 'chkrootkit -h && zsh'" \
           "dbpwaudit" "urxvt -e bash -c 'dbpwaudit -h && zsh'" \
           "DBPwAudit.jar" "urxvt -e bash -c 'DBPwAudit.jar && zsh'" \
           "exiv2" "urxvt -e bash -c 'exiv2 -h && zsh'" \
           "metacopy" "urxvt -e bash -c 'metacopy -h && zsh'" \
           "path-test" "urxvt -e bash -c 'path-test && zsh'" \
           "exiv2" "urxvt -e bash -c 'exiv2 -h && zsh'" \
           "metacopy" "urxvt -e bash -c 'metacopy -h && zsh'" \
           "path-test" "urxvt -e bash -c 'path-test && zsh'" \
           "inetsim" "urxvt -e bash -c 'inetsim --help && zsh'" \
           "jhead" "urxvt -e bash -c 'jhead -h && zsh'" \
           "jhead" "urxvt -e bash -c 'jhead -h && zsh'" \
           "malmon" "urxvt -e bash -c 'malmon -h && zsh'" \
           "malmon-scan" "urxvt -e bash -c 'malmon-scan && zsh'" \
           "mat" "urxvt -e bash -c 'mat -h && zsh'" \
           "mat-gui" "urxvt -e bash -c 'mat-gui && zsh'" \
           "nsia" "urxvt -e bash -c 'nsia -h && zsh'" \
           "nsia.jar" "urxvt -e bash -c 'nsia.jar && zsh'" \
           "onionshare" "urxvt -e bash -c 'onionshare -h && zsh'" \
           "onionshare-gui" "urxvt -e bash -c 'onionshare-gui && zsh'" \
           "portspoof" "urxvt -e bash -c 'portspoof -h && zsh'" \
           "rkhunter" "urxvt -e bash -c 'rkhunter -h && zsh'" \
           "rkhunter" "urxvt -e bash -c 'rkhunter -h && zsh'" \
           "sdel" "urxvt -e bash -c 'sdel -h && zsh'" \
           "sfill" "urxvt -e bash -c 'sfill -h && zsh'" \
           "smem-secure-delete" "urxvt -e bash -c 'smem-secure-delete -h && zsh'" \
           "srm" "urxvt -e bash -c 'srm -h && zsh'" \
           "sswap" "urxvt -e bash -c 'sswap -h && zsh'" \
           "the_cleaner.sh" "urxvt -e bash -c 'the_cleaner.sh -h && zsh'" \
           "sj-commit-results" "urxvt -e bash -c 'sj-commit-results -h && zsh'" \
           "sj-iptcpopt-probe" "urxvt -e bash -c 'sj-iptcpopt-probe -h && zsh'" \
           "sniffjoke" "urxvt -e bash -c 'sniffjoke -h && zsh'" \
           "sniffjoke-autotest" "urxvt -e bash -c 'sniffjoke-autotest -h && zsh'" \
           "sniffjokectl" "urxvt -e bash -c 'sniffjokectl -h && zsh'" \
           "snort" "urxvt -e bash -c 'snort -h && zsh'" \
           "u2boat" "urxvt -e bash -c 'u2boat && zsh'" \
           "u2spewfoo" "urxvt -e bash -c 'u2spewfoo && zsh'" \
           "suricata" "urxvt -e bash -c 'suricata && zsh'" \
           "tor-autocircuit" "urxvt -e bash -c 'tor-autocircuit && zsh'" \
           "truecrypt" "urxvt -e bash -c 'truecrypt -t -h && zsh'" \
           "truecrypt" "urxvt -e bash -c 'truecrypt -t -h && zsh'" \
           "vidalia" "urxvt -e bash -c 'vidalia && zsh'" \
           "vidalia" "urxvt -e bash -c 'vidalia && zsh'" \
           "wireless-ids" "urxvt -e bash -c 'wireless-ids -h && zsh'" \
           "wordpot" "urxvt -e bash -c 'wordpot -h && zsh'" \
