#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "dos" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "davoset" "urxvt -e bash -c 'davoset && zsh'" \
           "dnsdrdos" "urxvt -e bash -c 'dnsdrdos -H && zsh'" \
           "fhttp" "urxvt -e bash -c 'fhttp -h && zsh'" \
           "goldeneye" "urxvt -e bash -c 'goldeneye -h && zsh'" \
           "hulk" "urxvt -e bash -c 'hulk -h && zsh'" \
           "hawk" "urxvt -e bash -c 'hawk --help && zsh'" \
           "hwk-eagle" "urxvt -e bash -c 'hwk-eagle --help && zsh'" \
           "iaxflood" "urxvt -e bash -c 'iaxflood && zsh'" \
           "inviteflood" "urxvt -e bash -c 'inviteflood -h && zsh'" \
           "mz" "urxvt -e bash -c 'mz -h && zsh'" \
           "nkiller2" "urxvt -e bash -c 'nkiller2 -h && zsh'" \
           "phpstress" "urxvt -e bash -c 'phpstress -h && zsh'" \
           "bombardment" "urxvt -e bash -c 'bombardment && zsh'" \
           "siege" "urxvt -e bash -c 'siege -h && zsh'" \
           "siege.config" "urxvt -e bash -c 'siege.config && zsh'" \
           "siege2csv.pl" "urxvt -e bash -c 'siege2csv.pl && zsh'" \
           "bombardment" "urxvt -e bash -c 'bombardment && zsh'" \
           "siege" "urxvt -e bash -c 'siege -h && zsh'" \
           "siege.config" "urxvt -e bash -c 'siege.config && zsh'" \
           "siege2csv.pl" "urxvt -e bash -c 'siege2csv.pl && zsh'" \
           "slowhttptest" "urxvt -e bash -c 'slowhttptest -h && zsh'" \
           "slowloris" "urxvt -e bash -c 'slowloris && zsh'" \
           "sps" "urxvt -e bash -c 'sps -h && zsh'" \
           "synflood" "urxvt -e bash -c 'synflood -h && zsh'" \
           "synner" "urxvt -e bash -c 'synner -h && zsh'" \
           "t50" "urxvt -e bash -c 't50 --help && zsh'" \
           "get_mem_dump" "urxvt -e bash -c 'get_mem_dump && zsh'" \
           "tcgetkey" "urxvt -e bash -c 'tcgetkey && zsh'" \
           "6to4test.sh" "urxvt -e bash -c '6to4test.sh && zsh'" \
           "address6" "urxvt -e bash -c 'address6 && zsh'" \
           "alive6" "urxvt -e bash -c 'alive6 && zsh'" \
           "covert_send6" "urxvt -e bash -c 'covert_send6 && zsh'" \
           "covert_send6d" "urxvt -e bash -c 'covert_send6d && zsh'" \
           "denial6" "urxvt -e bash -c 'denial6 && zsh'" \
           "detect-new-ip6" "urxvt -e bash -c 'detect-new-ip6 && zsh'" \
           "detect_sniffer6" "urxvt -e bash -c 'detect_sniffer6 && zsh'" \
           "dnsdict6" "urxvt -e bash -c 'dnsdict6 && zsh'" \
           "dnsrevenum6" "urxvt -e bash -c 'dnsrevenum6 && zsh'" \
           "dnssecwalk" "urxvt -e bash -c 'dnssecwalk && zsh'" \
           "dos-new-ip6" "urxvt -e bash -c 'dos-new-ip6 && zsh'" \
           "dos_mld.sh" "urxvt -e bash -c 'dos_mld.sh && zsh'" \
           "dump_dhcp6" "urxvt -e bash -c 'dump_dhcp6 -h && zsh'" \
           "dump_router6" "urxvt -e bash -c 'dump_router6 && zsh'" \
           "exploit6" "urxvt -e bash -c 'exploit6 && zsh'" \
           "extract_hosts6.sh" "urxvt -e bash -c 'extract_hosts6.sh && zsh'" \
           "extract_networks6.sh" "urxvt -e bash -c 'extract_networks6.sh && zsh'" \
           "fake_advertise6" "urxvt -e bash -c 'fake_advertise6 && zsh'" \
           "fake_dhcps6" "urxvt -e bash -c 'fake_dhcps6 && zsh'" \
           "fake_dns6d" "urxvt -e bash -c 'fake_dns6d && zsh'" \
           "fake_dnsupdate6" "urxvt -e bash -c 'fake_dnsupdate6 && zsh'" \
           "fake_mipv6" "urxvt -e bash -c 'fake_mipv6 && zsh'" \
           "fake_mld26" "urxvt -e bash -c 'fake_mld26 && zsh'" \
           "fake_mld6" "urxvt -e bash -c 'fake_mld6 && zsh'" \
           "fake_mldrouter6" "urxvt -e bash -c 'fake_mldrouter6 && zsh'" \
           "fake_pim6" "urxvt -e bash -c 'fake_pim6 && zsh'" \
           "fake_router26" "urxvt -e bash -c 'fake_router26 && zsh'" \
           "fake_router6" "urxvt -e bash -c 'fake_router6 && zsh'" \
           "fake_solicitate6" "urxvt -e bash -c 'fake_solicitate6 && zsh'" \
           "firewall6" "urxvt -e bash -c 'firewall6 && zsh'" \
           "flood_advertise6" "urxvt -e bash -c 'flood_advertise6 && zsh'" \
           "flood_dhcpc6" "urxvt -e bash -c 'flood_dhcpc6 && zsh'" \
           "flood_mld26" "urxvt -e bash -c 'flood_mld26 && zsh'" \
           "flood_mld6" "urxvt -e bash -c 'flood_mld6 && zsh'" \
           "flood_mldrouter6" "urxvt -e bash -c 'flood_mldrouter6 && zsh'" \
           "flood_redir6" "urxvt -e bash -c 'flood_redir6 && zsh'" \
           "flood_router26" "urxvt -e bash -c 'flood_router26 && zsh'" \
           "flood_router6" "urxvt -e bash -c 'flood_router6 && zsh'" \
           "flood_rs6" "urxvt -e bash -c 'flood_rs6 && zsh'" \
           "flood_solicitate6" "urxvt -e bash -c 'flood_solicitate6 && zsh'" \
           "four2six" "urxvt -e bash -c 'four2six && zsh'" \
           "fragmentation6" "urxvt -e bash -c 'fragmentation6 && zsh'" \
           "fuzz_dhcpc6" "urxvt -e bash -c 'fuzz_dhcpc6 && zsh'" \
           "fuzz_dhcpc6-usage.pdf" "urxvt -e bash -c 'fuzz_dhcpc6-usage.pdf && zsh'" \
           "fuzz_dhcps6" "urxvt -e bash -c 'fuzz_dhcps6 && zsh'" \
           "fuzz_ip6" "urxvt -e bash -c 'fuzz_ip6 && zsh'" \
           "grep6.pl" "urxvt -e bash -c 'grep6.pl && zsh'" \
           "implementation6" "urxvt -e bash -c 'implementation6 && zsh'" \
           "implementation6d" "urxvt -e bash -c 'implementation6d && zsh'" \
           "inject_alive6" "urxvt -e bash -c 'inject_alive6 && zsh'" \
           "inverse_lookup6" "urxvt -e bash -c 'inverse_lookup6 && zsh'" \
           "kill_router6" "urxvt -e bash -c 'kill_router6 && zsh'" \
           "ndpexhaust26" "urxvt -e bash -c 'ndpexhaust26 && zsh'" \
           "ndpexhaust6" "urxvt -e bash -c 'ndpexhaust6 && zsh'" \
           "node_query6" "urxvt -e bash -c 'node_query6 && zsh'" \
           "parasite6" "urxvt -e bash -c 'parasite6 && zsh'" \
           "passive_discovery6" "urxvt -e bash -c 'passive_discovery6 && zsh'" \
           "randicmp6" "urxvt -e bash -c 'randicmp6 && zsh'" \
           "redir6" "urxvt -e bash -c 'redir6 && zsh'" \
           "redirsniff6" "urxvt -e bash -c 'redirsniff6 && zsh'" \
           "rsmurf6" "urxvt -e bash -c 'rsmurf6 && zsh'" \
           "sendpees6" "urxvt -e bash -c 'sendpees6 && zsh'" \
           "sendpeesmp6" "urxvt -e bash -c 'sendpeesmp6 && zsh'" \
           "six2four.sh" "urxvt -e bash -c 'six2four.sh && zsh'" \
           "smurf6" "urxvt -e bash -c 'smurf6 && zsh'" \
           "thc-ipv6-setup.sh" "urxvt -e bash -c 'thc-ipv6-setup.sh && zsh'" \
           "thcping6" "urxvt -e bash -c 'thcping6 && zsh'" \
           "thcsyn6" "urxvt -e bash -c 'thcsyn6 && zsh'" \
           "toobig6" "urxvt -e bash -c 'toobig6 && zsh'" \
           "trace6" "urxvt -e bash -c 'trace6 && zsh'" \
           "thc-ssl-dos" "urxvt -e bash -c 'thc-ssl-dos -h && zsh'" \
           "torshammer" "urxvt -e bash -c 'torshammer && zsh'" \
           "ufonet" "urxvt -e bash -c 'ufonet -h && zsh'" \
