#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "keylogger" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "llk" "urxvt -e bash -c 'llk && zsh'" \
           "llkk" "urxvt -e bash -c 'llkk && zsh'" \
           "logkeys" "urxvt -e bash -c 'logkeys -h && zsh'" \
           "logkeys-kill.sh" "urxvt -e bash -c 'logkeys-kill.sh && zsh'" \
           "logkeys-start.sh" "urxvt -e bash -c 'logkeys-start.sh && zsh'" \
           "xspy" "urxvt -e bash -c 'xspy -h && zsh'" \
