#!/bin/bash
source ~/.colors

~/.tools/ratmenu -label "sniffer" \
        -style dreary -fg "$COLOR11" -bg "$COLOR0"  \
           "androidsniffer" "urxvt -e bash -c 'androidsniffer -h && zsh'" \
           "argus" "urxvt -e bash -c 'argus -h && zsh'" \
           "argus-lsof" "urxvt -e bash -c 'argus-lsof && zsh'" \
           "argus-snmp" "urxvt -e bash -c 'argus-snmp && zsh'" \
           "argus-vmstat" "urxvt -e bash -c 'argus-vmstat && zsh'" \
           "argusbug" "urxvt -e bash -c 'argusbug && zsh'" \
           "argusclientbug" "urxvt -e bash -c 'argusclientbug && zsh'" \
           "ra" "urxvt -e bash -c 'ra -h && zsh'" \
           "rabins" "urxvt -e bash -c 'rabins -h && zsh'" \
           "racluster" "urxvt -e bash -c 'racluster -h && zsh'" \
           "raconvert" "urxvt -e bash -c 'raconvert -h && zsh'" \
           "racount" "urxvt -e bash -c 'racount -h && zsh'" \
           "radark" "urxvt -e bash -c 'radark -h && zsh'" \
           "radecode" "urxvt -e bash -c 'radecode && zsh'" \
           "radium" "urxvt -e bash -c 'radium -h && zsh'" \
           "radump" "urxvt -e bash -c 'radump && zsh'" \
           "raevent" "urxvt -e bash -c 'raevent -h && zsh'" \
           "rafilteraddr" "urxvt -e bash -c 'rafilteraddr && zsh'" \
           "ragraph" "urxvt -e bash -c 'ragraph && zsh'" \
           "ragrep" "urxvt -e bash -c 'ragrep && zsh'" \
           "rahisto" "urxvt -e bash -c 'rahisto && zsh'" \
           "rahosts" "urxvt -e bash -c 'rahosts && zsh'" \
           "ralabel" "urxvt -e bash -c 'ralabel && zsh'" \
           "ranonymize" "urxvt -e bash -c 'ranonymize && zsh'" \
           "rapath" "urxvt -e bash -c 'rapath && zsh'" \
           "rapolicy" "urxvt -e bash -c 'rapolicy && zsh'" \
           "raports" "urxvt -e bash -c 'raports && zsh'" \
           "rarpwatch" "urxvt -e bash -c 'rarpwatch && zsh'" \
           "raservices" "urxvt -e bash -c 'raservices && zsh'" \
           "rasort" "urxvt -e bash -c 'rasort -h && zsh'" \
           "rasplit" "urxvt -e bash -c 'rasplit -h && zsh'" \
           "rasql" "urxvt -e bash -c 'rasql -h && zsh'" \
           "rasqlinsert" "urxvt -e bash -c 'rasqlinsert && zsh'" \
           "rasqltimeindex" "urxvt -e bash -c 'rasqltimeindex && zsh'" \
           "rastream" "urxvt -e bash -c 'rastream -h && zsh'" \
           "rastrip" "urxvt -e bash -c 'rastrip -h && zsh'" \
           "ratemplate" "urxvt -e bash -c 'ratemplate && zsh'" \
           "ratimerange" "urxvt -e bash -c 'ratimerange && zsh'" \
           "ratop" "urxvt -e bash -c 'ratop && zsh'" \
           "rauserdata" "urxvt -e bash -c 'rauserdata && zsh'" \
           "bittwist" "urxvt -e bash -c 'bittwist -h && zsh'" \
           "bittwiste" "urxvt -e bash -c 'bittwiste -h && zsh'" \
           "captipper" "urxvt -e bash -c 'captipper && zsh'" \
           "cdpsnarf" "urxvt -e bash -c 'cdpsnarf -h && zsh'" \
           "chaosreader" "urxvt -e bash -c 'chaosreader -h && zsh'" \
           "creds-py" "urxvt -e bash -c 'creds-py -h && zsh'" \
           "darkstat" "urxvt -e bash -c 'darkstat -h && zsh'" \
           "darkstat" "urxvt -e bash -c 'darkstat -h && zsh'" \
           "driftnet" "urxvt -e bash -c 'driftnet -h && zsh'" \
           "arpspoof" "urxvt -e bash -c 'arpspoof && zsh'" \
           "dnsspoof" "urxvt -e bash -c 'dnsspoof -h && zsh'" \
           "dsniff" "urxvt -e bash -c 'dsniff -h && zsh'" \
           "filesnarf" "urxvt -e bash -c 'filesnarf -h && zsh'" \
           "macof" "urxvt -e bash -c 'macof -h && zsh'" \
           "mailsnarf" "urxvt -e bash -c 'mailsnarf -h && zsh'" \
           "msgsnarf" "urxvt -e bash -c 'msgsnarf -h && zsh'" \
           "sshmitm" "urxvt -e bash -c 'sshmitm -h && zsh'" \
           "sshow" "urxvt -e bash -c 'sshow -h && zsh'" \
           "tcpkill" "urxvt -e bash -c 'tcpkill -h && zsh'" \
           "tcpnice" "urxvt -e bash -c 'tcpnice -h && zsh'" \
           "urlsnarf" "urxvt -e bash -c 'urlsnarf -h && zsh'" \
           "webmitm" "urxvt -e bash -c 'webmitm -h && zsh'" \
           "webspy" "urxvt -e bash -c 'webspy -h && zsh'" \
           "arpspoof" "urxvt -e bash -c 'arpspoof && zsh'" \
           "dnsspoof" "urxvt -e bash -c 'dnsspoof -h && zsh'" \
           "dsniff" "urxvt -e bash -c 'dsniff -h && zsh'" \
           "filesnarf" "urxvt -e bash -c 'filesnarf -h && zsh'" \
           "macof" "urxvt -e bash -c 'macof -h && zsh'" \
           "mailsnarf" "urxvt -e bash -c 'mailsnarf -h && zsh'" \
           "msgsnarf" "urxvt -e bash -c 'msgsnarf -h && zsh'" \
           "sshmitm" "urxvt -e bash -c 'sshmitm -h && zsh'" \
           "sshow" "urxvt -e bash -c 'sshow -h && zsh'" \
           "tcpkill" "urxvt -e bash -c 'tcpkill -h && zsh'" \
           "tcpnice" "urxvt -e bash -c 'tcpnice -h && zsh'" \
           "urlsnarf" "urxvt -e bash -c 'urlsnarf -h && zsh'" \
           "webmitm" "urxvt -e bash -c 'webmitm -h && zsh'" \
           "webspy" "urxvt -e bash -c 'webspy -h && zsh'" \
           "etherape" "urxvt -e bash -c 'etherape && zsh'" \
           "etherape" "urxvt -e bash -c 'etherape && zsh'" \
           "ettercap" "urxvt -e bash -c 'ettercap -h && zsh'" \
           "etterfilter" "urxvt -e bash -c 'etterfilter -h && zsh'" \
           "etterlog" "urxvt -e bash -c 'etterlog -h && zsh'" \
           "ettercap" "urxvt -e bash -c 'ettercap -h && zsh'" \
           "etterfilter" "urxvt -e bash -c 'etterfilter -h && zsh'" \
           "etterlog" "urxvt -e bash -c 'etterlog -h && zsh'" \
           "fl0p" "urxvt -e bash -c 'fl0p -h && zsh'" \
           "flowinspect" "urxvt -e bash -c 'flowinspect -h && zsh'" \
           "fs-nyarl" "urxvt -e bash -c 'fs-nyarl -h && zsh'" \
           "chaosreader0.94" "urxvt -e bash -c 'chaosreader0.94 && zsh'" \
           "hdmi-sniff" "urxvt -e bash -c 'hdmi-sniff -h && zsh'" \
           "hex2raw" "urxvt -e bash -c 'hex2raw -h && zsh'" \
           "hexinject" "urxvt -e bash -c 'hexinject -h && zsh'" \
           "prettypacket" "urxvt -e bash -c 'prettypacket -h && zsh'" \
           "httpry" "urxvt -e bash -c 'httpry -h && zsh'" \
           "httpsniff" "urxvt -e bash -c 'httpsniff && zsh'" \
           "juncli" "urxvt -e bash -c 'juncli && zsh'" \
           "junkie" "urxvt -e bash -c 'junkie -h && zsh'" \
           "katsnoop" "urxvt -e bash -c 'katsnoop -h && zsh'" \
           "mfsniffer" "urxvt -e bash -c 'mfsniffer -h && zsh'" \
           "mitmap.sh" "urxvt -e bash -c 'mitmap.sh -h && zsh'" \
           "mitmer" "urxvt -e bash -c 'mitmer -h && zsh'" \
           "astraceroute" "urxvt -e bash -c 'astraceroute && zsh'" \
           "bpfc" "urxvt -e bash -c 'bpfc && zsh'" \
           "flowtop" "urxvt -e bash -c 'flowtop -h && zsh'" \
           "ifpps" "urxvt -e bash -c 'ifpps && zsh'" \
           "mausezahn" "urxvt -e bash -c 'mausezahn && zsh'" \
           "netsniff-ng" "urxvt -e bash -c 'netsniff-ng -h && zsh'" \
           "trafgen" "urxvt -e bash -c 'trafgen && zsh'" \
           "drone" "urxvt -e bash -c 'drone && zsh'" \
           "ostinato" "urxvt -e bash -c 'ostinato -h && zsh'" \
           "p0f" "urxvt -e bash -c 'p0f -h && zsh'" \
           "p0f-client" "urxvt -e bash -c 'p0f-client -h && zsh'" \
           "p0f-sendsyn" "urxvt -e bash -c 'p0f-sendsyn -h && zsh'" \
           "p0f-sendsyn6" "urxvt -e bash -c 'p0f-sendsyn6 && zsh'" \
           "passivedns" "urxvt -e bash -c 'passivedns -h && zsh'" \
           "PHoss" "urxvt -e bash -c 'PHoss -h && zsh'" \
           "pytacle" "urxvt -e bash -c 'pytacle && zsh'" \
           "sessionlist" "urxvt -e bash -c 'sessionlist && zsh'" \
           "snapception" "urxvt -e bash -c 'snapception --help && zsh'" \
           "sj-commit-results" "urxvt -e bash -c 'sj-commit-results -h && zsh'" \
           "sj-iptcpopt-probe" "urxvt -e bash -c 'sj-iptcpopt-probe -h && zsh'" \
           "sniffjoke" "urxvt -e bash -c 'sniffjoke -h && zsh'" \
           "sniffjoke-autotest" "urxvt -e bash -c 'sniffjoke-autotest -h && zsh'" \
           "sniffjokectl" "urxvt -e bash -c 'sniffjokectl -h && zsh'" \
           "snoopy" "urxvt -e bash -c 'snoopy && zsh'" \
           "snoopy-auth" "urxvt -e bash -c 'snoopy-auth && zsh'" \
           "sslstrip-snoopy" "urxvt -e bash -c 'sslstrip-snoopy && zsh'" \
           "ssl-phuck3r" "urxvt -e bash -c 'ssl-phuck3r -h && zsh'" \
           "ssldump" "urxvt -e bash -c 'ssldump -h && zsh'" \
           "sslsniff" "urxvt -e bash -c 'sslsniff && zsh'" \
           "sslstrip" "urxvt -e bash -c 'sslstrip -h && zsh'" \
           "mitm_listener" "urxvt -e bash -c 'mitm_listener && zsh'" \
           "tcpdump" "urxvt -e bash -c 'tcpdump -h && zsh'" \
           "tcpdump" "urxvt -e bash -c 'tcpdump -h && zsh'" \
           "tcpflow" "urxvt -e bash -c 'tcpflow -h && zsh'" \
           "tcpflow" "urxvt -e bash -c 'tcpflow -h && zsh'" \
           "tcpick" "urxvt -e bash -c 'tcpick --help && zsh'" \
           "tuxcut" "urxvt -e bash -c 'tuxcut && zsh'" \
           "wifi-monitor" "urxvt -e bash -c 'wifi-monitor -h && zsh'" \
           "wireless-ids" "urxvt -e bash -c 'wireless-ids -h && zsh'" \
           "capinfos" "urxvt -e bash -c 'capinfos -h && zsh'" \
           "captype" "urxvt -e bash -c 'captype && zsh'" \
           "dftest" "urxvt -e bash -c 'dftest && zsh'" \
           "dumpcap" "urxvt -e bash -c 'dumpcap && zsh'" \
           "editcap" "urxvt -e bash -c 'editcap && zsh'" \
           "mergecap" "urxvt -e bash -c 'mergecap -h && zsh'" \
           "randpkt" "urxvt -e bash -c 'randpkt && zsh'" \
           "rawshark" "urxvt -e bash -c 'rawshark && zsh'" \
           "reordercap" "urxvt -e bash -c 'reordercap && zsh'" \
           "text2pcap" "urxvt -e bash -c 'text2pcap && zsh'" \
           "tshark" "urxvt -e bash -c 'tshark -h && zsh'" \
           "capinfos" "urxvt -e bash -c 'capinfos -h && zsh'" \
           "captype" "urxvt -e bash -c 'captype && zsh'" \
           "dftest" "urxvt -e bash -c 'dftest && zsh'" \
           "dumpcap" "urxvt -e bash -c 'dumpcap && zsh'" \
           "editcap" "urxvt -e bash -c 'editcap && zsh'" \
           "mergecap" "urxvt -e bash -c 'mergecap -h && zsh'" \
           "randpkt" "urxvt -e bash -c 'randpkt && zsh'" \
           "rawshark" "urxvt -e bash -c 'rawshark && zsh'" \
           "reordercap" "urxvt -e bash -c 'reordercap && zsh'" \
           "text2pcap" "urxvt -e bash -c 'text2pcap && zsh'" \
           "tshark" "urxvt -e bash -c 'tshark -h && zsh'" \
           "wireshark" "urxvt -e bash -c 'wireshark && zsh'" \
           "wireshark" "urxvt -e bash -c 'wireshark && zsh'" \
           "xcavator" "urxvt -e bash -c 'xcavator -h && zsh'" \

