#!/bin/sh
while true;do
	if [ `battery -f '%i'` -lt 4 ] && ! [ -z ~/.dontshut ]; then
		touch ~/.dontshut
		zenity  --question --title "Battery"  --text "Battery if pretty fucking low, go to sleep?"
		if [ $? -ne 1 ];then
			pm-suspend
		fi
	else
	if [ -z ~/.dontshut ]
		rm ~/.dontshut
	fi
sleep 180;
done
