#! /bin/sh

. ./panel_colors
. ./icons
while read -r line ; do
	case $line in
		Imail) 
			mbsync -a > /dev/null
			mail="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_MAIL} %{B-}%{F-}"
			;;
		Iclear)
			priv=""
			pub=""
			face=""
			;;
		Ixlear)
			mail=''
		;;
		M*)
			notification="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
#		C*)
#			cpu="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} C:${line#?} %{B-}%{F-}"
#			;;
#		R*)
#			ram="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} R:${line#?} %{B-}%{F-}"
#			;;
	
#		S*)
#			signal="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} S:${line#?} %{B-}%{F-}"
#			;;
	
		p*)
			# playing mpc 
			paused=''
			playing="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_PLAY} ${line#?} %{B-}%{F-}"
			;;
	
		P*)
			# paused mpc
			playing=''
			paused="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_PAUSE} ${line#?} %{B-}%{F-}"
			;;
		K*)
			# volume output
			musicvol="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_MUSIC} ${line#?} %{B-}%{F-}"
			;;
	
	
                T*)
			level=${line#?}
                        if [ "$level" -gt 90 ];then
                          ICON_TEMP=$ICON_T4
                        elif [ "$level" -gt 65 ];then
                          ICON_TEMP=$ICON_T3
                        elif [ "$level" -gt 35 ];then
                          ICON_TEMP=$ICON_T2
                        elif [ "$level" -gt 15 ];then
                          ICON_TEMP=$ICON_T1
                        else
                          ICON_TEMP=$ICON_T0
                        fi
			temperature="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_TEMP} ${level} %{B-}%{F-}";
			;;

		BDischarging*)
			level=$(echo ${line#?} | cut -d' ' -f2)
                        if [ "$level" -gt 90 ];then
                          ICON_PWR=$ICON_BAT100
                        elif [ "$level" -gt 65 ];then
                          ICON_PWR=$ICON_BAT75
                        elif [ "$level" -gt 35 ];then
                          ICON_PWR=$ICON_BAT50
                        elif [ "$level" -gt 15 ];then
                          ICON_PWR=$ICON_BAT25
                        else
                          ICON_PWR=$ICON_BAT0
                        fi
			battery="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_PWR} ${level} %{B-}%{F-}";
			;;
	        B*)
			level=`echo ${line#?} | cut -d' ' -f2`
			battery="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_PLUG} ${level} %{B-}%{F-}";

			;;
	
	
		V*)
			# volume output
			if amixer contents | head -12 | tail -1 | grep on > /dev/null;then
			volume="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_HPHONES} ${line#?} %{B-}%{F-}"
		        else
			volume="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${ICON_VOLUME_UP} ${line#?} %{B-}%{F-}";
			fi
			;;
	
		E*)
			# essid output
                        if [ -z ${line#?} ];then 
			essid="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} E:No WiFi  %{B-}%{F-}"
                        else
			essid="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} E:${line#?} %{B-}%{F-}"
                        fi
			;;
	
		Z*)
			# clock output
			time_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
#		T*)
#			# xtitle output
#			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
#			;;
		D*)
			# active desktop
			desktop="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?}%{B-}%{F-}  "
          		;;
		Wclear)
			wm_infos=''
			;;
	
		\**)
			# current focused window
			wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FG}%{B$COLOR_FOCUSED_BG}%{U$COLOR_FOCUSED_UG}%{+o} ${line#?} %{-o}%{B-}%{F-}%{U-}"
			;;
		+*)
			# last focused window
			wm_infos="${wm_infos}%{F$COLOR_OTHER_FG}%{B$COLOR_OTHER_BG} ${line#?} %{B-}%{F-}"
			;;
        	-*)
			# other windows
			wm_infos="${wm_infos}%{F$COLOR_ELSE_FG}%{B$COLOR_ELSE_BG} ${line#?} %{B-}%{F-}"
			;;
#					u*)
#						# urgent desktop
#						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
#						;;
#					L*)
#						# layout
#						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
#						;;
	esac
	printf "%s\n" "%{l}${wm_infos}${title}%{r}${playing}${paused}${cpu}${ram}${essid}${signal}${volume}${musicvol}${temperature}${battery}${time_infos}             "
#	printf "%s\n" "%{l}${desktop}${wm_infos}%{r}${notification}${face}${priv}${pub}${mail}${playing}${paused}${cpu}${ram}${volume}${battery}${time_infos}"
done
