#! /bin/sh
cd ~/dotfiles/Panel/lemonbar
. ./profile
. ~/.colors

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo -m 777 "$PANEL_FIFO"


#bspc config top_padding $PANEL_HEIGHT
#bspc control --subscribe > "$PANEL_FIFO" &
./windows > "$PANEL_FIFO" &
#echo "D`rpws current`" > "$PANEL_FIFO" &
./volume > "$PANEL_FIFO" &
battery -i 60 -sf 'B%s %i' > "$PANEL_FIFO" &
clock -i 60 -sf 'Z%d %a %H:%M' > "$PANEL_FIFO" &
./music > "$PANEL_FIFO" &
./temp > "$PANEL_FIFO" &
#./load > "$PANEL_FIFO" &
#essid -sf 'E%s' -i 30 -w wlp2s0 > "$PANEL_FIFO" &
# ./signal > "$PANEL_FIFO" &
unbuffer alsactl monitor | grep --line-buffered 'Headphone Jack' | while read line; do volume -f 'V%i' > $PANEL_FIFO;done &                                                                    


. ./panel_colors

cat "$PANEL_FIFO" | ./panel_bar | lemonbar -f "$FONT_FONT" -f "$ICON_FONT" -g x$PANEL_HEIGHT -F "$COLOR11" -B "$COLOR0" -u 3 &

#sleep 1;
#stalonetray --geometry 1x1-415+2 --icon-gravity E --grow-gravity E  -bg $COLOR0 -i 20 &
