#!/bin/sh

while true;do

new=`mpc current` 

if mpc | grep -q playing; then  
symbol='p'
else
symbol='P'
fi

echo "$symbol`echo $new | cut --bytes 1-30`"
echo "K`mpc -h 127.0.0.1 volume | perl -pe 's/^volume://' | perl -pe 's/%$//' | perl -pe 's/^ //'`"
mpc idle > /dev/null
done
